/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DnsDNSCountRequest from '../model/DnsDNSCountRequest';
import DnsDomainRequest from '../model/DnsDomainRequest';
import DnsErrorResponse from '../model/DnsErrorResponse';
import V1DomainCountPost200Response from '../model/V1DomainCountPost200Response';
import V1DomainSearchPost200Response from '../model/V1DomainSearchPost200Response';
import V1DomainSubdomainSearchPost200Response from '../model/V1DomainSubdomainSearchPost200Response';
import V1DomainWhoisDomainNameGet200Response from '../model/V1DomainWhoisDomainNameGet200Response';
import V1DomainWhoisDomainNameHistoricalGet200Response from '../model/V1DomainWhoisDomainNameHistoricalGet200Response';
import V1DomainWhoisDomainNameIsExpiredGet200Response from '../model/V1DomainWhoisDomainNameIsExpiredGet200Response';

/**
* Domain service.
* @module odin/DomainApi
* @version 1.0
*/
export default class DomainApi {

    /**
    * Constructs a new DomainApi. 
    * @alias module:odin/DomainApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1DomainCountPost operation.
     * @callback module:odin/DomainApi~v1DomainCountPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1DomainCountPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get domains count
     * Get count of domain records based on query
     * @param {module:model/DnsDNSCountRequest} query Query
     * @param {module:odin/DomainApi~v1DomainCountPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1DomainCountPost200Response}
     */
    v1DomainCountPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1DomainCountPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1DomainCountPost200Response;
      return this.apiClient.callApi(
        '/v1/domain/count', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DomainSearchPost operation.
     * @callback module:odin/DomainApi~v1DomainSearchPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1DomainSearchPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search domains
     * Search domains based on the query
     * @param {module:model/DnsDomainRequest} query Query
     * @param {module:odin/DomainApi~v1DomainSearchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1DomainSearchPost200Response}
     */
    v1DomainSearchPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1DomainSearchPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1DomainSearchPost200Response;
      return this.apiClient.callApi(
        '/v1/domain/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DomainSubdomainCountPost operation.
     * @callback module:odin/DomainApi~v1DomainSubdomainCountPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1DomainCountPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch the total no. of subdomain records
     * Returns the count of subdomain records based on domain
     * @param {module:model/DnsDNSCountRequest} query Query
     * @param {module:odin/DomainApi~v1DomainSubdomainCountPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1DomainCountPost200Response}
     */
    v1DomainSubdomainCountPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1DomainSubdomainCountPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1DomainCountPost200Response;
      return this.apiClient.callApi(
        '/v1/domain/subdomain/count', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DomainSubdomainSearchPost operation.
     * @callback module:odin/DomainApi~v1DomainSubdomainSearchPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1DomainSubdomainSearchPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch the subdomain record
     * Returns the subdomain records based on query
     * @param {module:model/DnsDomainRequest} query Query
     * @param {module:odin/DomainApi~v1DomainSubdomainSearchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1DomainSubdomainSearchPost200Response}
     */
    v1DomainSubdomainSearchPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1DomainSubdomainSearchPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1DomainSubdomainSearchPost200Response;
      return this.apiClient.callApi(
        '/v1/domain/subdomain/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DomainWhoisDomainNameGet operation.
     * @callback module:odin/DomainApi~v1DomainWhoisDomainNameGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1DomainWhoisDomainNameGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch the domain whois record details
     * Provides extensive details about the domain whois record like name servers, domain status, registrar, etc.
     * @param {String} domainName domain
     * @param {module:odin/DomainApi~v1DomainWhoisDomainNameGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1DomainWhoisDomainNameGet200Response}
     */
    v1DomainWhoisDomainNameGet(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v1DomainWhoisDomainNameGet");
      }

      let pathParams = {
        'domain-name': domainName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1DomainWhoisDomainNameGet200Response;
      return this.apiClient.callApi(
        '/v1/domain/whois/{domain-name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DomainWhoisDomainNameHistoricalGet operation.
     * @callback module:odin/DomainApi~v1DomainWhoisDomainNameHistoricalGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1DomainWhoisDomainNameHistoricalGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch all the domain whois historical records
     * Provides historical details about the domain whois record like name servers, domain status, registrar, etc
     * @param {String} domainName domain
     * @param {module:odin/DomainApi~v1DomainWhoisDomainNameHistoricalGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1DomainWhoisDomainNameHistoricalGet200Response}
     */
    v1DomainWhoisDomainNameHistoricalGet(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v1DomainWhoisDomainNameHistoricalGet");
      }

      let pathParams = {
        'domain-name': domainName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1DomainWhoisDomainNameHistoricalGet200Response;
      return this.apiClient.callApi(
        '/v1/domain/whois/{domain-name}/historical', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DomainWhoisDomainNameIsExpiredGet operation.
     * @callback module:odin/DomainApi~v1DomainWhoisDomainNameIsExpiredGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1DomainWhoisDomainNameIsExpiredGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the expiry for a particular domain
     * Provides historical details about the domain whois record like name servers, domain status, registrar, etc
     * @param {String} domainName domain
     * @param {module:odin/DomainApi~v1DomainWhoisDomainNameIsExpiredGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1DomainWhoisDomainNameIsExpiredGet200Response}
     */
    v1DomainWhoisDomainNameIsExpiredGet(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v1DomainWhoisDomainNameIsExpiredGet");
      }

      let pathParams = {
        'domain-name': domainName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1DomainWhoisDomainNameIsExpiredGet200Response;
      return this.apiClient.callApi(
        '/v1/domain/whois/{domain-name}/is-expired', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1DomainWhoisDomainNameIsRegisteredGet operation.
     * @callback module:odin/DomainApi~v1DomainWhoisDomainNameIsRegisteredGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1DomainWhoisDomainNameIsExpiredGet200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch all the domain whois historical records
     * Provides historical details about the domain whois record like name servers, domain status, registrar, etc
     * @param {String} domainName domain
     * @param {module:odin/DomainApi~v1DomainWhoisDomainNameIsRegisteredGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1DomainWhoisDomainNameIsExpiredGet200Response}
     */
    v1DomainWhoisDomainNameIsRegisteredGet(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v1DomainWhoisDomainNameIsRegisteredGet");
      }

      let pathParams = {
        'domain-name': domainName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1DomainWhoisDomainNameIsExpiredGet200Response;
      return this.apiClient.callApi(
        '/v1/domain/whois/{domain-name}/is-registered', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
