/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ExposedCountRequest from '../model/ExposedCountRequest';
import ExposedFileAPIResponse from '../model/ExposedFileAPIResponse';
import ExposedSearchRequest from '../model/ExposedSearchRequest';
import ExposedSummaryRequest from '../model/ExposedSummaryRequest';
import V1ExposedBucketsCountPost200Response from '../model/V1ExposedBucketsCountPost200Response';
import V1ExposedBucketsSummaryPost200Response from '../model/V1ExposedBucketsSummaryPost200Response';

/**
* ExposedFiles service.
* @module odin/ExposedFilesApi
* @version 1.0
*/
export default class ExposedFilesApi {

    /**
    * Constructs a new ExposedFilesApi. 
    * @alias module:odin/ExposedFilesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ExposedFilesCountPost operation.
     * @callback module:odin/ExposedFilesApi~v1ExposedFilesCountPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ExposedBucketsCountPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get file count
     * Returns overall count of exposed bucket files according to filters
     * @param {module:model/ExposedCountRequest} query Count Request
     * @param {module:odin/ExposedFilesApi~v1ExposedFilesCountPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ExposedBucketsCountPost200Response}
     */
    v1ExposedFilesCountPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1ExposedFilesCountPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ExposedBucketsCountPost200Response;
      return this.apiClient.callApi(
        '/v1/exposed/files/count', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ExposedFilesSearchPost operation.
     * @callback module:odin/ExposedFilesApi~v1ExposedFilesSearchPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExposedFileAPIResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search exposed files
     * Search exposed files using advanved filters Search across categories {img, aud, vid, font, txt, doc, src, db, march, arch, 3d, exec, key, cert} Search across labels {credential, financial, pii, legal, ip, medical, hr, report, confidential, backup, compromised, vulnerable} Search across providers {aws, gcp, do, linode}
     * @param {module:model/ExposedSearchRequest} query Search Query
     * @param {module:odin/ExposedFilesApi~v1ExposedFilesSearchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExposedFileAPIResponse}
     */
    v1ExposedFilesSearchPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1ExposedFilesSearchPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ExposedFileAPIResponse;
      return this.apiClient.callApi(
        '/v1/exposed/files/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ExposedFilesSummaryPost operation.
     * @callback module:odin/ExposedFilesApi~v1ExposedFilesSummaryPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ExposedBucketsSummaryPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get file summary
     * Returns a summary of exposed bucket files according to provided filters
     * @param {module:model/ExposedSummaryRequest} query Summary Request
     * @param {module:odin/ExposedFilesApi~v1ExposedFilesSummaryPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ExposedBucketsSummaryPost200Response}
     */
    v1ExposedFilesSummaryPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1ExposedFilesSummaryPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ExposedBucketsSummaryPost200Response;
      return this.apiClient.callApi(
        '/v1/exposed/files/summary', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
