/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ExposedBucketAPIResponse from '../model/ExposedBucketAPIResponse';
import ExposedCountRequest from '../model/ExposedCountRequest';
import ExposedSearchRequest from '../model/ExposedSearchRequest';
import ExposedSummaryRequest from '../model/ExposedSummaryRequest';
import V1ExposedBucketsCountPost200Response from '../model/V1ExposedBucketsCountPost200Response';
import V1ExposedBucketsSummaryPost200Response from '../model/V1ExposedBucketsSummaryPost200Response';

/**
* ExposedBuckets service.
* @module odin/ExposedBucketsApi
* @version 1.0
*/
export default class ExposedBucketsApi {

    /**
    * Constructs a new ExposedBucketsApi. 
    * @alias module:odin/ExposedBucketsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v1ExposedBucketsCountPost operation.
     * @callback module:odin/ExposedBucketsApi~v1ExposedBucketsCountPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ExposedBucketsCountPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get exposed bucket count
     * Get exposed bucket count according to provided filters
     * @param {module:model/ExposedCountRequest} query Count Request
     * @param {module:odin/ExposedBucketsApi~v1ExposedBucketsCountPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ExposedBucketsCountPost200Response}
     */
    v1ExposedBucketsCountPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1ExposedBucketsCountPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ExposedBucketsCountPost200Response;
      return this.apiClient.callApi(
        '/v1/exposed/buckets/count', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ExposedBucketsSearchPost operation.
     * @callback module:odin/ExposedBucketsApi~v1ExposedBucketsSearchPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExposedBucketAPIResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search exposed buckets
     * Search exposed buckets according to provided filters Search across categories {img, aud, vid, font, doc, src, web, bkup, dbdump} Search across labels {credential, financial, pii, legal, ip, medical, hr, report, confidential, backup, compromised, vulnerable} Search across providers {aws, gcp, do, linode}
     * @param {module:model/ExposedSearchRequest} query Search Query
     * @param {module:odin/ExposedBucketsApi~v1ExposedBucketsSearchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExposedBucketAPIResponse}
     */
    v1ExposedBucketsSearchPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1ExposedBucketsSearchPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ExposedBucketAPIResponse;
      return this.apiClient.callApi(
        '/v1/exposed/buckets/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v1ExposedBucketsSummaryPost operation.
     * @callback module:odin/ExposedBucketsApi~v1ExposedBucketsSummaryPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/V1ExposedBucketsSummaryPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Exposed buckets summary
     * Get Returns exposed buckets aggregated count according to filters
     * @param {module:model/ExposedSummaryRequest} query Summary Request
     * @param {module:odin/ExposedBucketsApi~v1ExposedBucketsSummaryPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/V1ExposedBucketsSummaryPost200Response}
     */
    v1ExposedBucketsSummaryPost(query, callback) {
      let postBody = query;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling v1ExposedBucketsSummaryPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = V1ExposedBucketsSummaryPost200Response;
      return this.apiClient.callApi(
        '/v1/exposed/buckets/summary', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
