/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage model module.
 * @module model/CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage
 * @version 1.0
 */
class CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage {
    /**
     * Constructs a new <code>CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage</code>.
     * @alias module:model/CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage
     */
    constructor() { 
        
        CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage} The populated <code>CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage();

            if (data.hasOwnProperty('digital_signature')) {
                obj['digital_signature'] = ApiClient.convertToType(data['digital_signature'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} digital_signature
 */
CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage.prototype['digital_signature'] = undefined;






export default CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage;

