/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificate from './CertificateCertificateHashResponseDataCertificate';

/**
 * The CertificateCertificateHashResponseData model module.
 * @module model/CertificateCertificateHashResponseData
 * @version 1.0
 */
class CertificateCertificateHashResponseData {
    /**
     * Constructs a new <code>CertificateCertificateHashResponseData</code>.
     * @alias module:model/CertificateCertificateHashResponseData
     */
    constructor() { 
        
        CertificateCertificateHashResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateHashResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateHashResponseData} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateHashResponseData} The populated <code>CertificateCertificateHashResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateHashResponseData();

            if (data.hasOwnProperty('certificate')) {
                obj['certificate'] = CertificateCertificateHashResponseDataCertificate.constructFromObject(data['certificate']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateHashResponseData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateHashResponseData</code>.
     */
    static validateJSON(data) {
        // validate the optional field `certificate`
        if (data['certificate']) { // data not null
          CertificateCertificateHashResponseDataCertificate.validateJSON(data['certificate']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }

        return true;
    }


}



/**
 * @member {module:model/CertificateCertificateHashResponseDataCertificate} certificate
 */
CertificateCertificateHashResponseData.prototype['certificate'] = undefined;

/**
 * @member {Array.<String>} tags
 */
CertificateCertificateHashResponseData.prototype['tags'] = undefined;






export default CertificateCertificateHashResponseData;

