/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm from './CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm';

/**
 * The CertificateCertificateHashResponseDataCertificateSignature model module.
 * @module model/CertificateCertificateHashResponseDataCertificateSignature
 * @version 1.0
 */
class CertificateCertificateHashResponseDataCertificateSignature {
    /**
     * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSignature</code>.
     * @alias module:model/CertificateCertificateHashResponseDataCertificateSignature
     */
    constructor() { 
        
        CertificateCertificateHashResponseDataCertificateSignature.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateHashResponseDataCertificateSignature</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateHashResponseDataCertificateSignature} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateHashResponseDataCertificateSignature} The populated <code>CertificateCertificateHashResponseDataCertificateSignature</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateHashResponseDataCertificateSignature();

            if (data.hasOwnProperty('signature_algorithm')) {
                obj['signature_algorithm'] = CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm.constructFromObject(data['signature_algorithm']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateHashResponseDataCertificateSignature</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateHashResponseDataCertificateSignature</code>.
     */
    static validateJSON(data) {
        // validate the optional field `signature_algorithm`
        if (data['signature_algorithm']) { // data not null
          CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm.validateJSON(data['signature_algorithm']);
        }

        return true;
    }


}



/**
 * @member {module:model/CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm} signature_algorithm
 */
CertificateCertificateHashResponseDataCertificateSignature.prototype['signature_algorithm'] = undefined;






export default CertificateCertificateHashResponseDataCertificateSignature;

