/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificateCertScroll model module.
 * @module model/CertificateCertScroll
 * @version 1.0
 */
class CertificateCertScroll {
    /**
     * Constructs a new <code>CertificateCertScroll</code>.
     * @alias module:model/CertificateCertScroll
     */
    constructor() { 
        
        CertificateCertScroll.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertScroll</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertScroll} obj Optional instance to populate.
     * @return {module:model/CertificateCertScroll} The populated <code>CertificateCertScroll</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertScroll();

            if (data.hasOwnProperty('certificates')) {
                obj['certificates'] = ApiClient.convertToType(data['certificates'], [Object]);
            }
            if (data.hasOwnProperty('next_batch')) {
                obj['next_batch'] = ApiClient.convertToType(data['next_batch'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertScroll</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertScroll</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['certificates'])) {
            throw new Error("Expected the field `certificates` to be an array in the JSON data but got " + data['certificates']);
        }
        // ensure the json data is a string
        if (data['next_batch'] && !(typeof data['next_batch'] === 'string' || data['next_batch'] instanceof String)) {
            throw new Error("Expected the field `next_batch` to be a primitive type in the JSON string but got " + data['next_batch']);
        }

        return true;
    }


}



/**
 * @member {Array.<Object>} certificates
 */
CertificateCertScroll.prototype['certificates'] = undefined;

/**
 * @member {String} next_batch
 */
CertificateCertScroll.prototype['next_batch'] = undefined;






export default CertificateCertScroll;

