/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner model module.
 * @module model/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner
 * @version 1.0
 */
class CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner {
    /**
     * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner</code>.
     * @alias module:model/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner
     */
    constructor() { 
        
        CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner} The populated <code>CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner();

            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('fld')) {
                obj['fld'] = ApiClient.convertToType(data['fld'], 'String');
            }
            if (data.hasOwnProperty('subdomain')) {
                obj['subdomain'] = ApiClient.convertToType(data['subdomain'], 'String');
            }
            if (data.hasOwnProperty('tld')) {
                obj['tld'] = ApiClient.convertToType(data['tld'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // ensure the json data is a string
        if (data['fld'] && !(typeof data['fld'] === 'string' || data['fld'] instanceof String)) {
            throw new Error("Expected the field `fld` to be a primitive type in the JSON string but got " + data['fld']);
        }
        // ensure the json data is a string
        if (data['subdomain'] && !(typeof data['subdomain'] === 'string' || data['subdomain'] instanceof String)) {
            throw new Error("Expected the field `subdomain` to be a primitive type in the JSON string but got " + data['subdomain']);
        }
        // ensure the json data is a string
        if (data['tld'] && !(typeof data['tld'] === 'string' || data['tld'] instanceof String)) {
            throw new Error("Expected the field `tld` to be a primitive type in the JSON string but got " + data['tld']);
        }

        return true;
    }


}



/**
 * @member {String} domain
 */
CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner.prototype['domain'] = undefined;

/**
 * @member {String} fld
 */
CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner.prototype['fld'] = undefined;

/**
 * @member {String} subdomain
 */
CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner.prototype['subdomain'] = undefined;

/**
 * @member {String} tld
 */
CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner.prototype['tld'] = undefined;






export default CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner;

