/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage model module.
 * @module model/CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage
 * @version 1.0
 */
class CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage {
    /**
     * Constructs a new <code>CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage</code>.
     * @alias module:model/CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage
     */
    constructor() { 
        
        CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage} The populated <code>CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage();

            if (data.hasOwnProperty('client_auth')) {
                obj['client_auth'] = ApiClient.convertToType(data['client_auth'], 'Boolean');
            }
            if (data.hasOwnProperty('server_auth')) {
                obj['server_auth'] = ApiClient.convertToType(data['server_auth'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} client_auth
 */
CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage.prototype['client_auth'] = undefined;

/**
 * @member {Boolean} server_auth
 */
CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage.prototype['server_auth'] = undefined;






export default CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage;

