/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName from './CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName';
import CertificateCertificateHashResponseDataCertificateIssuer from './CertificateCertificateHashResponseDataCertificateIssuer';
import CertificateCertificateHashResponseDataCertificateSubject from './CertificateCertificateHashResponseDataCertificateSubject';
import CertificateCertificateHashResponseDataCertificateValidity from './CertificateCertificateHashResponseDataCertificateValidity';

/**
 * The CertificateCertificateSearchData model module.
 * @module model/CertificateCertificateSearchData
 * @version 1.0
 */
class CertificateCertificateSearchData {
    /**
     * Constructs a new <code>CertificateCertificateSearchData</code>.
     * @alias module:model/CertificateCertificateSearchData
     */
    constructor() { 
        
        CertificateCertificateSearchData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateSearchData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateSearchData} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateSearchData} The populated <code>CertificateCertificateSearchData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateSearchData();

            if (data.hasOwnProperty('fingerprint_md5')) {
                obj['fingerprint_md5'] = ApiClient.convertToType(data['fingerprint_md5'], 'String');
            }
            if (data.hasOwnProperty('fingerprint_sha1')) {
                obj['fingerprint_sha1'] = ApiClient.convertToType(data['fingerprint_sha1'], 'String');
            }
            if (data.hasOwnProperty('fingerprint_sha256')) {
                obj['fingerprint_sha256'] = ApiClient.convertToType(data['fingerprint_sha256'], 'String');
            }
            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = CertificateCertificateHashResponseDataCertificateIssuer.constructFromObject(data['issuer']);
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = CertificateCertificateHashResponseDataCertificateSubject.constructFromObject(data['subject']);
            }
            if (data.hasOwnProperty('subject_alt_name')) {
                obj['subject_alt_name'] = CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName.constructFromObject(data['subject_alt_name']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('validity')) {
                obj['validity'] = CertificateCertificateHashResponseDataCertificateValidity.constructFromObject(data['validity']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateSearchData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateSearchData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['fingerprint_md5'] && !(typeof data['fingerprint_md5'] === 'string' || data['fingerprint_md5'] instanceof String)) {
            throw new Error("Expected the field `fingerprint_md5` to be a primitive type in the JSON string but got " + data['fingerprint_md5']);
        }
        // ensure the json data is a string
        if (data['fingerprint_sha1'] && !(typeof data['fingerprint_sha1'] === 'string' || data['fingerprint_sha1'] instanceof String)) {
            throw new Error("Expected the field `fingerprint_sha1` to be a primitive type in the JSON string but got " + data['fingerprint_sha1']);
        }
        // ensure the json data is a string
        if (data['fingerprint_sha256'] && !(typeof data['fingerprint_sha256'] === 'string' || data['fingerprint_sha256'] instanceof String)) {
            throw new Error("Expected the field `fingerprint_sha256` to be a primitive type in the JSON string but got " + data['fingerprint_sha256']);
        }
        // validate the optional field `issuer`
        if (data['issuer']) { // data not null
          CertificateCertificateHashResponseDataCertificateIssuer.validateJSON(data['issuer']);
        }
        // validate the optional field `subject`
        if (data['subject']) { // data not null
          CertificateCertificateHashResponseDataCertificateSubject.validateJSON(data['subject']);
        }
        // validate the optional field `subject_alt_name`
        if (data['subject_alt_name']) { // data not null
          CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName.validateJSON(data['subject_alt_name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['tags'])) {
            throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
        }
        // validate the optional field `validity`
        if (data['validity']) { // data not null
          CertificateCertificateHashResponseDataCertificateValidity.validateJSON(data['validity']);
        }

        return true;
    }


}



/**
 * @member {String} fingerprint_md5
 */
CertificateCertificateSearchData.prototype['fingerprint_md5'] = undefined;

/**
 * @member {String} fingerprint_sha1
 */
CertificateCertificateSearchData.prototype['fingerprint_sha1'] = undefined;

/**
 * @member {String} fingerprint_sha256
 */
CertificateCertificateSearchData.prototype['fingerprint_sha256'] = undefined;

/**
 * @member {module:model/CertificateCertificateHashResponseDataCertificateIssuer} issuer
 */
CertificateCertificateSearchData.prototype['issuer'] = undefined;

/**
 * @member {module:model/CertificateCertificateHashResponseDataCertificateSubject} subject
 */
CertificateCertificateSearchData.prototype['subject'] = undefined;

/**
 * @member {module:model/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName} subject_alt_name
 */
CertificateCertificateSearchData.prototype['subject_alt_name'] = undefined;

/**
 * @member {Array.<String>} tags
 */
CertificateCertificateSearchData.prototype['tags'] = undefined;

/**
 * @member {module:model/CertificateCertificateHashResponseDataCertificateValidity} validity
 */
CertificateCertificateSearchData.prototype['validity'] = undefined;






export default CertificateCertificateSearchData;

