/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner model module.
 * @module model/CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner
 * @version 1.0
 */
class CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner {
    /**
     * Constructs a new <code>CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner</code>.
     * @alias module:model/CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner
     */
    constructor() { 
        
        CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner} The populated <code>CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner();

            if (data.hasOwnProperty('cps')) {
                obj['cps'] = ApiClient.convertToType(data['cps'], ['String']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['cps'])) {
            throw new Error("Expected the field `cps` to be an array in the JSON data but got " + data['cps']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} cps
 */
CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner.prototype['cps'] = undefined;

/**
 * @member {String} id
 */
CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner.prototype['id'] = undefined;






export default CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner;

