/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner from './CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner';

/**
 * The CertificateCertificateHashResponseDataCertificateSubjectAltName model module.
 * @module model/CertificateCertificateHashResponseDataCertificateSubjectAltName
 * @version 1.0
 */
class CertificateCertificateHashResponseDataCertificateSubjectAltName {
    /**
     * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSubjectAltName</code>.
     * @alias module:model/CertificateCertificateHashResponseDataCertificateSubjectAltName
     */
    constructor() { 
        
        CertificateCertificateHashResponseDataCertificateSubjectAltName.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateHashResponseDataCertificateSubjectAltName</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateHashResponseDataCertificateSubjectAltName} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateHashResponseDataCertificateSubjectAltName} The populated <code>CertificateCertificateHashResponseDataCertificateSubjectAltName</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateHashResponseDataCertificateSubjectAltName();

            if (data.hasOwnProperty('dns_names')) {
                obj['dns_names'] = ApiClient.convertToType(data['dns_names'], ['String']);
            }
            if (data.hasOwnProperty('extended_dns_names')) {
                obj['extended_dns_names'] = ApiClient.convertToType(data['extended_dns_names'], [CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateHashResponseDataCertificateSubjectAltName</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateHashResponseDataCertificateSubjectAltName</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['dns_names'])) {
            throw new Error("Expected the field `dns_names` to be an array in the JSON data but got " + data['dns_names']);
        }
        if (data['extended_dns_names']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['extended_dns_names'])) {
                throw new Error("Expected the field `extended_dns_names` to be an array in the JSON data but got " + data['extended_dns_names']);
            }
            // validate the optional field `extended_dns_names` (array)
            for (const item of data['extended_dns_names']) {
                CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<String>} dns_names
 */
CertificateCertificateHashResponseDataCertificateSubjectAltName.prototype['dns_names'] = undefined;

/**
 * @member {Array.<module:model/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNamesInner>} extended_dns_names
 */
CertificateCertificateHashResponseDataCertificateSubjectAltName.prototype['extended_dns_names'] = undefined;






export default CertificateCertificateHashResponseDataCertificateSubjectAltName;

