/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName model module.
 * @module model/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName
 * @version 1.0
 */
class CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName {
    /**
     * Constructs a new <code>CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName</code>.
     * @alias module:model/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName
     */
    constructor() { 
        
        CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName} The populated <code>CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName();

            if (data.hasOwnProperty('dns_names')) {
                obj['dns_names'] = ApiClient.convertToType(data['dns_names'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['dns_names'])) {
            throw new Error("Expected the field `dns_names` to be an array in the JSON data but got " + data['dns_names']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} dns_names
 */
CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName.prototype['dns_names'] = undefined;






export default CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName;

