/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateSearchResponsePagination model module.
 * @module model/CertificateCertificateSearchResponsePagination
 * @version 1.0
 */
class CertificateCertificateSearchResponsePagination {
    /**
     * Constructs a new <code>CertificateCertificateSearchResponsePagination</code>.
     * @alias module:model/CertificateCertificateSearchResponsePagination
     */
    constructor() { 
        
        CertificateCertificateSearchResponsePagination.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateCertificateSearchResponsePagination</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateCertificateSearchResponsePagination} obj Optional instance to populate.
     * @return {module:model/CertificateCertificateSearchResponsePagination} The populated <code>CertificateCertificateSearchResponsePagination</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateCertificateSearchResponsePagination();

            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], ['Number']);
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], ['Number']);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateCertificateSearchResponsePagination</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateCertificateSearchResponsePagination</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['last'])) {
            throw new Error("Expected the field `last` to be an array in the JSON data but got " + data['last']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['start'])) {
            throw new Error("Expected the field `start` to be an array in the JSON data but got " + data['start']);
        }

        return true;
    }


}



/**
 * @member {Array.<Number>} last
 */
CertificateCertificateSearchResponsePagination.prototype['last'] = undefined;

/**
 * @member {Number} limit
 */
CertificateCertificateSearchResponsePagination.prototype['limit'] = undefined;

/**
 * @member {Array.<Number>} start
 */
CertificateCertificateSearchResponsePagination.prototype['start'] = undefined;

/**
 * @member {Number} total
 */
CertificateCertificateSearchResponsePagination.prototype['total'] = undefined;






export default CertificateCertificateSearchResponsePagination;

