/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Encoding model module.
 * @module model/Encoding
 * @version 1.0
 */
class Encoding {
    /**
     * Constructs a new <code>Encoding</code>.
     * @alias module:model/Encoding
     */
    constructor() { 
        
        Encoding.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Encoding</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Encoding} obj Optional instance to populate.
     * @return {module:model/Encoding} The populated <code>Encoding</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Encoding();

            if (data.hasOwnProperty('raw')) {
                obj['raw'] = ApiClient.convertToType(data['raw'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Encoding</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Encoding</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['raw'] && !(typeof data['raw'] === 'string' || data['raw'] instanceof String)) {
            throw new Error("Expected the field `raw` to be a primitive type in the JSON string but got " + data['raw']);
        }

        return true;
    }


}



/**
 * @member {String} raw
 */
Encoding.prototype['raw'] = undefined;






export default Encoding;

