/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EshandlerEXTDNSName from './EshandlerEXTDNSName';

/**
 * The EshandlerDNS model module.
 * @module model/EshandlerDNS
 * @version 1.0
 */
class EshandlerDNS {
    /**
     * Constructs a new <code>EshandlerDNS</code>.
     * @alias module:model/EshandlerDNS
     */
    constructor() { 
        
        EshandlerDNS.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EshandlerDNS</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EshandlerDNS} obj Optional instance to populate.
     * @return {module:model/EshandlerDNS} The populated <code>EshandlerDNS</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EshandlerDNS();

            if (data.hasOwnProperty('added_at')) {
                obj['added_at'] = ApiClient.convertToType(data['added_at'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
            }
            if (data.hasOwnProperty('ext_dns_name')) {
                obj['ext_dns_name'] = EshandlerEXTDNSName.constructFromObject(data['ext_dns_name']);
            }
            if (data.hasOwnProperty('subdomain')) {
                obj['subdomain'] = ApiClient.convertToType(data['subdomain'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EshandlerDNS</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EshandlerDNS</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['added_at'] && !(typeof data['added_at'] === 'string' || data['added_at'] instanceof String)) {
            throw new Error("Expected the field `added_at` to be a primitive type in the JSON string but got " + data['added_at']);
        }
        // ensure the json data is a string
        if (data['domain'] && !(typeof data['domain'] === 'string' || data['domain'] instanceof String)) {
            throw new Error("Expected the field `domain` to be a primitive type in the JSON string but got " + data['domain']);
        }
        // validate the optional field `ext_dns_name`
        if (data['ext_dns_name']) { // data not null
          EshandlerEXTDNSName.validateJSON(data['ext_dns_name']);
        }
        // ensure the json data is a string
        if (data['subdomain'] && !(typeof data['subdomain'] === 'string' || data['subdomain'] instanceof String)) {
            throw new Error("Expected the field `subdomain` to be a primitive type in the JSON string but got " + data['subdomain']);
        }

        return true;
    }


}



/**
 * @member {String} added_at
 */
EshandlerDNS.prototype['added_at'] = undefined;

/**
 * @member {String} domain
 */
EshandlerDNS.prototype['domain'] = undefined;

/**
 * @member {module:model/EshandlerEXTDNSName} ext_dns_name
 */
EshandlerDNS.prototype['ext_dns_name'] = undefined;

/**
 * @member {String} subdomain
 */
EshandlerDNS.prototype['subdomain'] = undefined;






export default EshandlerDNS;

