/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExposedAPIResponse model module.
 * @module model/ExposedAPIResponse
 * @version 1.0
 */
class ExposedAPIResponse {
    /**
     * Constructs a new <code>ExposedAPIResponse</code>.
     * @alias module:model/ExposedAPIResponse
     */
    constructor() { 
        
        ExposedAPIResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExposedAPIResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExposedAPIResponse} obj Optional instance to populate.
     * @return {module:model/ExposedAPIResponse} The populated <code>ExposedAPIResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExposedAPIResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = ApiClient.convertToType(data['pagination'], Object);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExposedAPIResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExposedAPIResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Object} data
 */
ExposedAPIResponse.prototype['data'] = undefined;

/**
 * @member {Object} pagination
 */
ExposedAPIResponse.prototype['pagination'] = undefined;

/**
 * @member {Boolean} success
 */
ExposedAPIResponse.prototype['success'] = undefined;






export default ExposedAPIResponse;

