/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExposedFile model module.
 * @module model/ExposedFile
 * @version 1.0
 */
class ExposedFile {
    /**
     * Constructs a new <code>ExposedFile</code>.
     * @alias module:model/ExposedFile
     */
    constructor() { 
        
        ExposedFile.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExposedFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExposedFile} obj Optional instance to populate.
     * @return {module:model/ExposedFile} The populated <code>ExposedFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExposedFile();

            if (data.hasOwnProperty('accessible')) {
                obj['accessible'] = ApiClient.convertToType(data['accessible'], 'Boolean');
            }
            if (data.hasOwnProperty('bucket')) {
                obj['bucket'] = ApiClient.convertToType(data['bucket'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('etag')) {
                obj['etag'] = ApiClient.convertToType(data['etag'], 'String');
            }
            if (data.hasOwnProperty('ext')) {
                obj['ext'] = ApiClient.convertToType(data['ext'], 'String');
            }
            if (data.hasOwnProperty('ext_desc')) {
                obj['ext_desc'] = ApiClient.convertToType(data['ext_desc'], 'String');
            }
            if (data.hasOwnProperty('ins_at')) {
                obj['ins_at'] = ApiClient.convertToType(data['ins_at'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('mod_at')) {
                obj['mod_at'] = ApiClient.convertToType(data['mod_at'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('scan_at')) {
                obj['scan_at'] = ApiClient.convertToType(data['scan_at'], 'String');
            }
            if (data.hasOwnProperty('sensitive')) {
                obj['sensitive'] = ApiClient.convertToType(data['sensitive'], 'Boolean');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExposedFile</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExposedFile</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['bucket'] && !(typeof data['bucket'] === 'string' || data['bucket'] instanceof String)) {
            throw new Error("Expected the field `bucket` to be a primitive type in the JSON string but got " + data['bucket']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }
        // ensure the json data is a string
        if (data['etag'] && !(typeof data['etag'] === 'string' || data['etag'] instanceof String)) {
            throw new Error("Expected the field `etag` to be a primitive type in the JSON string but got " + data['etag']);
        }
        // ensure the json data is a string
        if (data['ext'] && !(typeof data['ext'] === 'string' || data['ext'] instanceof String)) {
            throw new Error("Expected the field `ext` to be a primitive type in the JSON string but got " + data['ext']);
        }
        // ensure the json data is a string
        if (data['ext_desc'] && !(typeof data['ext_desc'] === 'string' || data['ext_desc'] instanceof String)) {
            throw new Error("Expected the field `ext_desc` to be a primitive type in the JSON string but got " + data['ext_desc']);
        }
        // ensure the json data is a string
        if (data['ins_at'] && !(typeof data['ins_at'] === 'string' || data['ins_at'] instanceof String)) {
            throw new Error("Expected the field `ins_at` to be a primitive type in the JSON string but got " + data['ins_at']);
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // ensure the json data is a string
        if (data['mod_at'] && !(typeof data['mod_at'] === 'string' || data['mod_at'] instanceof String)) {
            throw new Error("Expected the field `mod_at` to be a primitive type in the JSON string but got " + data['mod_at']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // ensure the json data is a string
        if (data['provider'] && !(typeof data['provider'] === 'string' || data['provider'] instanceof String)) {
            throw new Error("Expected the field `provider` to be a primitive type in the JSON string but got " + data['provider']);
        }
        // ensure the json data is a string
        if (data['region'] && !(typeof data['region'] === 'string' || data['region'] instanceof String)) {
            throw new Error("Expected the field `region` to be a primitive type in the JSON string but got " + data['region']);
        }
        // ensure the json data is a string
        if (data['scan_at'] && !(typeof data['scan_at'] === 'string' || data['scan_at'] instanceof String)) {
            throw new Error("Expected the field `scan_at` to be a primitive type in the JSON string but got " + data['scan_at']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}



/**
 * @member {Boolean} accessible
 */
ExposedFile.prototype['accessible'] = undefined;

/**
 * @member {String} bucket
 */
ExposedFile.prototype['bucket'] = undefined;

/**
 * @member {String} category
 */
ExposedFile.prototype['category'] = undefined;

/**
 * @member {String} etag
 */
ExposedFile.prototype['etag'] = undefined;

/**
 * @member {String} ext
 */
ExposedFile.prototype['ext'] = undefined;

/**
 * @member {String} ext_desc
 */
ExposedFile.prototype['ext_desc'] = undefined;

/**
 * @member {String} ins_at
 */
ExposedFile.prototype['ins_at'] = undefined;

/**
 * @member {String} label
 */
ExposedFile.prototype['label'] = undefined;

/**
 * @member {String} mod_at
 */
ExposedFile.prototype['mod_at'] = undefined;

/**
 * @member {String} name
 */
ExposedFile.prototype['name'] = undefined;

/**
 * @member {String} path
 */
ExposedFile.prototype['path'] = undefined;

/**
 * @member {String} provider
 */
ExposedFile.prototype['provider'] = undefined;

/**
 * @member {String} region
 */
ExposedFile.prototype['region'] = undefined;

/**
 * @member {String} scan_at
 */
ExposedFile.prototype['scan_at'] = undefined;

/**
 * @member {Boolean} sensitive
 */
ExposedFile.prototype['sensitive'] = undefined;

/**
 * @member {Number} size
 */
ExposedFile.prototype['size'] = undefined;

/**
 * @member {String} type
 */
ExposedFile.prototype['type'] = undefined;

/**
 * @member {String} url
 */
ExposedFile.prototype['url'] = undefined;






export default ExposedFile;

