/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IpservicesHostsSummaryResponseData from './IpservicesHostsSummaryResponseData';

/**
 * The IpservicesHostsSummaryResponse model module.
 * @module model/IpservicesHostsSummaryResponse
 * @version 1.0
 */
class IpservicesHostsSummaryResponse {
    /**
     * Constructs a new <code>IpservicesHostsSummaryResponse</code>.
     * @alias module:model/IpservicesHostsSummaryResponse
     */
    constructor() { 
        
        IpservicesHostsSummaryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IpservicesHostsSummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IpservicesHostsSummaryResponse} obj Optional instance to populate.
     * @return {module:model/IpservicesHostsSummaryResponse} The populated <code>IpservicesHostsSummaryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IpservicesHostsSummaryResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = IpservicesHostsSummaryResponseData.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IpservicesHostsSummaryResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IpservicesHostsSummaryResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          IpservicesHostsSummaryResponseData.validateJSON(data['data']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * @member {module:model/IpservicesHostsSummaryResponseData} data
 */
IpservicesHostsSummaryResponse.prototype['data'] = undefined;

/**
 * @member {String} message
 */
IpservicesHostsSummaryResponse.prototype['message'] = undefined;

/**
 * @member {Boolean} success
 */
IpservicesHostsSummaryResponse.prototype['success'] = undefined;






export default IpservicesHostsSummaryResponse;

