/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IPASN from './IPASN';
import IPDomain from './IPDomain';
import IPHostname from './IPHostname';
import IPLocation from './IPLocation';
import IPService from './IPService';
import IPTag from './IPTag';
import IPWhois from './IPWhois';

/**
 * The IpservicesIPSummaryData model module.
 * @module model/IpservicesIPSummaryData
 * @version 1.0
 */
class IpservicesIPSummaryData {
    /**
     * Constructs a new <code>IpservicesIPSummaryData</code>.
     * @alias module:model/IpservicesIPSummaryData
     */
    constructor() { 
        
        IpservicesIPSummaryData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IpservicesIPSummaryData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IpservicesIPSummaryData} obj Optional instance to populate.
     * @return {module:model/IpservicesIPSummaryData} The populated <code>IpservicesIPSummaryData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IpservicesIPSummaryData();

            if (data.hasOwnProperty('asn')) {
                obj['asn'] = IPASN.constructFromObject(data['asn']);
            }
            if (data.hasOwnProperty('asn_updated_at')) {
                obj['asn_updated_at'] = ApiClient.convertToType(data['asn_updated_at'], 'String');
            }
            if (data.hasOwnProperty('banner')) {
                obj['banner'] = ApiClient.convertToType(data['banner'], ['String']);
            }
            if (data.hasOwnProperty('domains')) {
                obj['domains'] = ApiClient.convertToType(data['domains'], [IPDomain]);
            }
            if (data.hasOwnProperty('hostnames')) {
                obj['hostnames'] = ApiClient.convertToType(data['hostnames'], [IPHostname]);
            }
            if (data.hasOwnProperty('ip')) {
                obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
            }
            if (data.hasOwnProperty('is_ipv4')) {
                obj['is_ipv4'] = ApiClient.convertToType(data['is_ipv4'], 'Boolean');
            }
            if (data.hasOwnProperty('is_ipv6')) {
                obj['is_ipv6'] = ApiClient.convertToType(data['is_ipv6'], 'Boolean');
            }
            if (data.hasOwnProperty('is_vuln')) {
                obj['is_vuln'] = ApiClient.convertToType(data['is_vuln'], 'Boolean');
            }
            if (data.hasOwnProperty('last_updated_at')) {
                obj['last_updated_at'] = ApiClient.convertToType(data['last_updated_at'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = IPLocation.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('location_updated_at')) {
                obj['location_updated_at'] = ApiClient.convertToType(data['location_updated_at'], 'String');
            }
            if (data.hasOwnProperty('scan_id')) {
                obj['scan_id'] = ApiClient.convertToType(data['scan_id'], 'Number');
            }
            if (data.hasOwnProperty('services')) {
                obj['services'] = ApiClient.convertToType(data['services'], [IPService]);
            }
            if (data.hasOwnProperty('services_hash')) {
                obj['services_hash'] = ApiClient.convertToType(data['services_hash'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [IPTag]);
            }
            if (data.hasOwnProperty('whois')) {
                obj['whois'] = IPWhois.constructFromObject(data['whois']);
            }
            if (data.hasOwnProperty('whois_updated_at')) {
                obj['whois_updated_at'] = ApiClient.convertToType(data['whois_updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IpservicesIPSummaryData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IpservicesIPSummaryData</code>.
     */
    static validateJSON(data) {
        // validate the optional field `asn`
        if (data['asn']) { // data not null
          IPASN.validateJSON(data['asn']);
        }
        // ensure the json data is a string
        if (data['asn_updated_at'] && !(typeof data['asn_updated_at'] === 'string' || data['asn_updated_at'] instanceof String)) {
            throw new Error("Expected the field `asn_updated_at` to be a primitive type in the JSON string but got " + data['asn_updated_at']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['banner'])) {
            throw new Error("Expected the field `banner` to be an array in the JSON data but got " + data['banner']);
        }
        if (data['domains']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['domains'])) {
                throw new Error("Expected the field `domains` to be an array in the JSON data but got " + data['domains']);
            }
            // validate the optional field `domains` (array)
            for (const item of data['domains']) {
                IPDomain.validateJSON(item);
            };
        }
        if (data['hostnames']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['hostnames'])) {
                throw new Error("Expected the field `hostnames` to be an array in the JSON data but got " + data['hostnames']);
            }
            // validate the optional field `hostnames` (array)
            for (const item of data['hostnames']) {
                IPHostname.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['ip'] && !(typeof data['ip'] === 'string' || data['ip'] instanceof String)) {
            throw new Error("Expected the field `ip` to be a primitive type in the JSON string but got " + data['ip']);
        }
        // ensure the json data is a string
        if (data['last_updated_at'] && !(typeof data['last_updated_at'] === 'string' || data['last_updated_at'] instanceof String)) {
            throw new Error("Expected the field `last_updated_at` to be a primitive type in the JSON string but got " + data['last_updated_at']);
        }
        // validate the optional field `location`
        if (data['location']) { // data not null
          IPLocation.validateJSON(data['location']);
        }
        // ensure the json data is a string
        if (data['location_updated_at'] && !(typeof data['location_updated_at'] === 'string' || data['location_updated_at'] instanceof String)) {
            throw new Error("Expected the field `location_updated_at` to be a primitive type in the JSON string but got " + data['location_updated_at']);
        }
        if (data['services']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['services'])) {
                throw new Error("Expected the field `services` to be an array in the JSON data but got " + data['services']);
            }
            // validate the optional field `services` (array)
            for (const item of data['services']) {
                IPService.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['services_hash'] && !(typeof data['services_hash'] === 'string' || data['services_hash'] instanceof String)) {
            throw new Error("Expected the field `services_hash` to be a primitive type in the JSON string but got " + data['services_hash']);
        }
        if (data['tags']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tags'])) {
                throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
            }
            // validate the optional field `tags` (array)
            for (const item of data['tags']) {
                IPTag.validateJSON(item);
            };
        }
        // validate the optional field `whois`
        if (data['whois']) { // data not null
          IPWhois.validateJSON(data['whois']);
        }
        // ensure the json data is a string
        if (data['whois_updated_at'] && !(typeof data['whois_updated_at'] === 'string' || data['whois_updated_at'] instanceof String)) {
            throw new Error("Expected the field `whois_updated_at` to be a primitive type in the JSON string but got " + data['whois_updated_at']);
        }

        return true;
    }


}



/**
 * @member {module:model/IPASN} asn
 */
IpservicesIPSummaryData.prototype['asn'] = undefined;

/**
 * @member {String} asn_updated_at
 */
IpservicesIPSummaryData.prototype['asn_updated_at'] = undefined;

/**
 * @member {Array.<String>} banner
 */
IpservicesIPSummaryData.prototype['banner'] = undefined;

/**
 * @member {Array.<module:model/IPDomain>} domains
 */
IpservicesIPSummaryData.prototype['domains'] = undefined;

/**
 * @member {Array.<module:model/IPHostname>} hostnames
 */
IpservicesIPSummaryData.prototype['hostnames'] = undefined;

/**
 * @member {String} ip
 */
IpservicesIPSummaryData.prototype['ip'] = undefined;

/**
 * @member {Boolean} is_ipv4
 */
IpservicesIPSummaryData.prototype['is_ipv4'] = undefined;

/**
 * @member {Boolean} is_ipv6
 */
IpservicesIPSummaryData.prototype['is_ipv6'] = undefined;

/**
 * @member {Boolean} is_vuln
 */
IpservicesIPSummaryData.prototype['is_vuln'] = undefined;

/**
 * @member {String} last_updated_at
 */
IpservicesIPSummaryData.prototype['last_updated_at'] = undefined;

/**
 * @member {module:model/IPLocation} location
 */
IpservicesIPSummaryData.prototype['location'] = undefined;

/**
 * @member {String} location_updated_at
 */
IpservicesIPSummaryData.prototype['location_updated_at'] = undefined;

/**
 * @member {Number} scan_id
 */
IpservicesIPSummaryData.prototype['scan_id'] = undefined;

/**
 * @member {Array.<module:model/IPService>} services
 */
IpservicesIPSummaryData.prototype['services'] = undefined;

/**
 * @member {String} services_hash
 */
IpservicesIPSummaryData.prototype['services_hash'] = undefined;

/**
 * @member {Array.<module:model/IPTag>} tags
 */
IpservicesIPSummaryData.prototype['tags'] = undefined;

/**
 * @member {module:model/IPWhois} whois
 */
IpservicesIPSummaryData.prototype['whois'] = undefined;

/**
 * @member {String} whois_updated_at
 */
IpservicesIPSummaryData.prototype['whois_updated_at'] = undefined;






export default IpservicesIPSummaryData;

