/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IPTag model module.
 * @module model/IPTag
 * @version 1.0
 */
class IPTag {
    /**
     * Constructs a new <code>IPTag</code>.
     * @alias module:model/IPTag
     */
    constructor() { 
        
        IPTag.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IPTag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IPTag} obj Optional instance to populate.
     * @return {module:model/IPTag} The populated <code>IPTag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IPTag();

            if (data.hasOwnProperty('last_updated_at')) {
                obj['last_updated_at'] = ApiClient.convertToType(data['last_updated_at'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pretty_name')) {
                obj['pretty_name'] = ApiClient.convertToType(data['pretty_name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IPTag</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IPTag</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['last_updated_at'] && !(typeof data['last_updated_at'] === 'string' || data['last_updated_at'] instanceof String)) {
            throw new Error("Expected the field `last_updated_at` to be a primitive type in the JSON string but got " + data['last_updated_at']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['pretty_name'] && !(typeof data['pretty_name'] === 'string' || data['pretty_name'] instanceof String)) {
            throw new Error("Expected the field `pretty_name` to be a primitive type in the JSON string but got " + data['pretty_name']);
        }

        return true;
    }


}



/**
 * @member {String} last_updated_at
 */
IPTag.prototype['last_updated_at'] = undefined;

/**
 * @member {String} name
 */
IPTag.prototype['name'] = undefined;

/**
 * @member {String} pretty_name
 */
IPTag.prototype['pretty_name'] = undefined;

/**
 * @member {Boolean} value
 */
IPTag.prototype['value'] = undefined;






export default IPTag;

