/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Encoding from './Encoding';

/**
 * The IPWhois model module.
 * @module model/IPWhois
 * @version 1.0
 */
class IPWhois {
    /**
     * Constructs a new <code>IPWhois</code>.
     * @alias module:model/IPWhois
     */
    constructor() { 
        
        IPWhois.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IPWhois</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IPWhois} obj Optional instance to populate.
     * @return {module:model/IPWhois} The populated <code>IPWhois</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IPWhois();

            if (data.hasOwnProperty('_encoding')) {
                obj['_encoding'] = Encoding.constructFromObject(data['_encoding']);
            }
            if (data.hasOwnProperty('descr')) {
                obj['descr'] = ApiClient.convertToType(data['descr'], 'String');
            }
            if (data.hasOwnProperty('network')) {
                obj['network'] = ApiClient.convertToType(data['network'], 'String');
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = ApiClient.convertToType(data['organization'], 'String');
            }
            if (data.hasOwnProperty('raw')) {
                obj['raw'] = ApiClient.convertToType(data['raw'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IPWhois</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IPWhois</code>.
     */
    static validateJSON(data) {
        // validate the optional field `_encoding`
        if (data['_encoding']) { // data not null
          Encoding.validateJSON(data['_encoding']);
        }
        // ensure the json data is a string
        if (data['descr'] && !(typeof data['descr'] === 'string' || data['descr'] instanceof String)) {
            throw new Error("Expected the field `descr` to be a primitive type in the JSON string but got " + data['descr']);
        }
        // ensure the json data is a string
        if (data['network'] && !(typeof data['network'] === 'string' || data['network'] instanceof String)) {
            throw new Error("Expected the field `network` to be a primitive type in the JSON string but got " + data['network']);
        }
        // ensure the json data is a string
        if (data['organization'] && !(typeof data['organization'] === 'string' || data['organization'] instanceof String)) {
            throw new Error("Expected the field `organization` to be a primitive type in the JSON string but got " + data['organization']);
        }
        // ensure the json data is a string
        if (data['raw'] && !(typeof data['raw'] === 'string' || data['raw'] instanceof String)) {
            throw new Error("Expected the field `raw` to be a primitive type in the JSON string but got " + data['raw']);
        }

        return true;
    }


}



/**
 * @member {module:model/Encoding} _encoding
 */
IPWhois.prototype['_encoding'] = undefined;

/**
 * @member {String} descr
 */
IPWhois.prototype['descr'] = undefined;

/**
 * @member {String} network
 */
IPWhois.prototype['network'] = undefined;

/**
 * @member {String} organization
 */
IPWhois.prototype['organization'] = undefined;

/**
 * @member {String} raw
 */
IPWhois.prototype['raw'] = undefined;






export default IPWhois;

