/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceFullCveData from './ServiceFullCveData';
import ServiceIPASN from './ServiceIPASN';
import ServiceIPDomain from './ServiceIPDomain';
import ServiceIPHostname from './ServiceIPHostname';
import ServiceIPLocation from './ServiceIPLocation';
import ServiceIPServiceMeta from './ServiceIPServiceMeta';
import ServiceIPServiceSoftware from './ServiceIPServiceSoftware';
import ServiceIPTag from './ServiceIPTag';
import ServiceIPWhois from './ServiceIPWhois';

/**
 * The ServiceService model module.
 * @module model/ServiceService
 * @version 1.0
 */
class ServiceService {
    /**
     * Constructs a new <code>ServiceService</code>.
     * @alias module:model/ServiceService
     */
    constructor() { 
        
        ServiceService.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceService</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceService} obj Optional instance to populate.
     * @return {module:model/ServiceService} The populated <code>ServiceService</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceService();

            if (data.hasOwnProperty('_meta')) {
                obj['_meta'] = ServiceIPServiceMeta.constructFromObject(data['_meta']);
            }
            if (data.hasOwnProperty('asn')) {
                obj['asn'] = ServiceIPASN.constructFromObject(data['asn']);
            }
            if (data.hasOwnProperty('asn_updated_at')) {
                obj['asn_updated_at'] = ApiClient.convertToType(data['asn_updated_at'], 'String');
            }
            if (data.hasOwnProperty('banners')) {
                obj['banners'] = ApiClient.convertToType(data['banners'], ['String']);
            }
            if (data.hasOwnProperty('cve')) {
                obj['cve'] = ApiClient.convertToType(data['cve'], [ServiceFullCveData]);
            }
            if (data.hasOwnProperty('domains')) {
                obj['domains'] = ApiClient.convertToType(data['domains'], [ServiceIPDomain]);
            }
            if (data.hasOwnProperty('extra_info')) {
                obj['extra_info'] = ApiClient.convertToType(data['extra_info'], 'String');
            }
            if (data.hasOwnProperty('hostnames')) {
                obj['hostnames'] = ApiClient.convertToType(data['hostnames'], [ServiceIPHostname]);
            }
            if (data.hasOwnProperty('ip')) {
                obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
            }
            if (data.hasOwnProperty('is_ipv4')) {
                obj['is_ipv4'] = ApiClient.convertToType(data['is_ipv4'], 'Boolean');
            }
            if (data.hasOwnProperty('is_ipv6')) {
                obj['is_ipv6'] = ApiClient.convertToType(data['is_ipv6'], 'Boolean');
            }
            if (data.hasOwnProperty('is_vuln')) {
                obj['is_vuln'] = ApiClient.convertToType(data['is_vuln'], 'Boolean');
            }
            if (data.hasOwnProperty('last_updated_at')) {
                obj['last_updated_at'] = ApiClient.convertToType(data['last_updated_at'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ServiceIPLocation.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('location_updated_at')) {
                obj['location_updated_at'] = ApiClient.convertToType(data['location_updated_at'], 'String');
            }
            if (data.hasOwnProperty('modules')) {
                obj['modules'] = ApiClient.convertToType(data['modules'], {'String': Object});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ApiClient.convertToType(data['product'], 'String');
            }
            if (data.hasOwnProperty('protocol')) {
                obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
            }
            if (data.hasOwnProperty('scan_id')) {
                obj['scan_id'] = ApiClient.convertToType(data['scan_id'], 'Number');
            }
            if (data.hasOwnProperty('softwares')) {
                obj['softwares'] = ApiClient.convertToType(data['softwares'], [ServiceIPServiceSoftware]);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [ServiceIPTag]);
            }
            if (data.hasOwnProperty('tunnel')) {
                obj['tunnel'] = ApiClient.convertToType(data['tunnel'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('whois')) {
                obj['whois'] = ServiceIPWhois.constructFromObject(data['whois']);
            }
            if (data.hasOwnProperty('whois_updated_at')) {
                obj['whois_updated_at'] = ApiClient.convertToType(data['whois_updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceService</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceService</code>.
     */
    static validateJSON(data) {
        // validate the optional field `_meta`
        if (data['_meta']) { // data not null
          ServiceIPServiceMeta.validateJSON(data['_meta']);
        }
        // validate the optional field `asn`
        if (data['asn']) { // data not null
          ServiceIPASN.validateJSON(data['asn']);
        }
        // ensure the json data is a string
        if (data['asn_updated_at'] && !(typeof data['asn_updated_at'] === 'string' || data['asn_updated_at'] instanceof String)) {
            throw new Error("Expected the field `asn_updated_at` to be a primitive type in the JSON string but got " + data['asn_updated_at']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['banners'])) {
            throw new Error("Expected the field `banners` to be an array in the JSON data but got " + data['banners']);
        }
        if (data['cve']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cve'])) {
                throw new Error("Expected the field `cve` to be an array in the JSON data but got " + data['cve']);
            }
            // validate the optional field `cve` (array)
            for (const item of data['cve']) {
                ServiceFullCveData.validateJSON(item);
            };
        }
        if (data['domains']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['domains'])) {
                throw new Error("Expected the field `domains` to be an array in the JSON data but got " + data['domains']);
            }
            // validate the optional field `domains` (array)
            for (const item of data['domains']) {
                ServiceIPDomain.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['extra_info'] && !(typeof data['extra_info'] === 'string' || data['extra_info'] instanceof String)) {
            throw new Error("Expected the field `extra_info` to be a primitive type in the JSON string but got " + data['extra_info']);
        }
        if (data['hostnames']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['hostnames'])) {
                throw new Error("Expected the field `hostnames` to be an array in the JSON data but got " + data['hostnames']);
            }
            // validate the optional field `hostnames` (array)
            for (const item of data['hostnames']) {
                ServiceIPHostname.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['ip'] && !(typeof data['ip'] === 'string' || data['ip'] instanceof String)) {
            throw new Error("Expected the field `ip` to be a primitive type in the JSON string but got " + data['ip']);
        }
        // ensure the json data is a string
        if (data['last_updated_at'] && !(typeof data['last_updated_at'] === 'string' || data['last_updated_at'] instanceof String)) {
            throw new Error("Expected the field `last_updated_at` to be a primitive type in the JSON string but got " + data['last_updated_at']);
        }
        // validate the optional field `location`
        if (data['location']) { // data not null
          ServiceIPLocation.validateJSON(data['location']);
        }
        // ensure the json data is a string
        if (data['location_updated_at'] && !(typeof data['location_updated_at'] === 'string' || data['location_updated_at'] instanceof String)) {
            throw new Error("Expected the field `location_updated_at` to be a primitive type in the JSON string but got " + data['location_updated_at']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['product'] && !(typeof data['product'] === 'string' || data['product'] instanceof String)) {
            throw new Error("Expected the field `product` to be a primitive type in the JSON string but got " + data['product']);
        }
        // ensure the json data is a string
        if (data['protocol'] && !(typeof data['protocol'] === 'string' || data['protocol'] instanceof String)) {
            throw new Error("Expected the field `protocol` to be a primitive type in the JSON string but got " + data['protocol']);
        }
        if (data['softwares']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['softwares'])) {
                throw new Error("Expected the field `softwares` to be an array in the JSON data but got " + data['softwares']);
            }
            // validate the optional field `softwares` (array)
            for (const item of data['softwares']) {
                ServiceIPServiceSoftware.validateJSON(item);
            };
        }
        if (data['tags']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tags'])) {
                throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
            }
            // validate the optional field `tags` (array)
            for (const item of data['tags']) {
                ServiceIPTag.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['tunnel'] && !(typeof data['tunnel'] === 'string' || data['tunnel'] instanceof String)) {
            throw new Error("Expected the field `tunnel` to be a primitive type in the JSON string but got " + data['tunnel']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }
        // validate the optional field `whois`
        if (data['whois']) { // data not null
          ServiceIPWhois.validateJSON(data['whois']);
        }
        // ensure the json data is a string
        if (data['whois_updated_at'] && !(typeof data['whois_updated_at'] === 'string' || data['whois_updated_at'] instanceof String)) {
            throw new Error("Expected the field `whois_updated_at` to be a primitive type in the JSON string but got " + data['whois_updated_at']);
        }

        return true;
    }


}



/**
 * @member {module:model/ServiceIPServiceMeta} _meta
 */
ServiceService.prototype['_meta'] = undefined;

/**
 * @member {module:model/ServiceIPASN} asn
 */
ServiceService.prototype['asn'] = undefined;

/**
 * @member {String} asn_updated_at
 */
ServiceService.prototype['asn_updated_at'] = undefined;

/**
 * @member {Array.<String>} banners
 */
ServiceService.prototype['banners'] = undefined;

/**
 * @member {Array.<module:model/ServiceFullCveData>} cve
 */
ServiceService.prototype['cve'] = undefined;

/**
 * @member {Array.<module:model/ServiceIPDomain>} domains
 */
ServiceService.prototype['domains'] = undefined;

/**
 * @member {String} extra_info
 */
ServiceService.prototype['extra_info'] = undefined;

/**
 * @member {Array.<module:model/ServiceIPHostname>} hostnames
 */
ServiceService.prototype['hostnames'] = undefined;

/**
 * @member {String} ip
 */
ServiceService.prototype['ip'] = undefined;

/**
 * @member {Boolean} is_ipv4
 */
ServiceService.prototype['is_ipv4'] = undefined;

/**
 * @member {Boolean} is_ipv6
 */
ServiceService.prototype['is_ipv6'] = undefined;

/**
 * @member {Boolean} is_vuln
 */
ServiceService.prototype['is_vuln'] = undefined;

/**
 * @member {String} last_updated_at
 */
ServiceService.prototype['last_updated_at'] = undefined;

/**
 * @member {module:model/ServiceIPLocation} location
 */
ServiceService.prototype['location'] = undefined;

/**
 * @member {String} location_updated_at
 */
ServiceService.prototype['location_updated_at'] = undefined;

/**
 * services.tls -> services.modules.tls key names - if you mess up the key names
 * @member {Object.<String, Object>} modules
 */
ServiceService.prototype['modules'] = undefined;

/**
 * @member {String} name
 */
ServiceService.prototype['name'] = undefined;

/**
 * @member {Number} port
 */
ServiceService.prototype['port'] = undefined;

/**
 * @member {String} product
 */
ServiceService.prototype['product'] = undefined;

/**
 * @member {String} protocol
 */
ServiceService.prototype['protocol'] = undefined;

/**
 * @member {Number} scan_id
 */
ServiceService.prototype['scan_id'] = undefined;

/**
 * @member {Array.<module:model/ServiceIPServiceSoftware>} softwares
 */
ServiceService.prototype['softwares'] = undefined;

/**
 * @member {Array.<module:model/ServiceIPTag>} tags
 */
ServiceService.prototype['tags'] = undefined;

/**
 * @member {String} tunnel
 */
ServiceService.prototype['tunnel'] = undefined;

/**
 * @member {String} version
 */
ServiceService.prototype['version'] = undefined;

/**
 * @member {module:model/ServiceIPWhois} whois
 */
ServiceService.prototype['whois'] = undefined;

/**
 * @member {String} whois_updated_at
 */
ServiceService.prototype['whois_updated_at'] = undefined;






export default ServiceService;

