/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CertificateAPIResponse from './CertificateAPIResponse';
import CertificateCertCount from './CertificateCertCount';

/**
 * The V1CertificatesCountPost200Response model module.
 * @module model/V1CertificatesCountPost200Response
 * @version 1.0
 */
class V1CertificatesCountPost200Response {
    /**
     * Constructs a new <code>V1CertificatesCountPost200Response</code>.
     * @alias module:model/V1CertificatesCountPost200Response
     * @implements module:model/CertificateAPIResponse
     */
    constructor() { 
        CertificateAPIResponse.initialize(this);
        V1CertificatesCountPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1CertificatesCountPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1CertificatesCountPost200Response} obj Optional instance to populate.
     * @return {module:model/V1CertificatesCountPost200Response} The populated <code>V1CertificatesCountPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1CertificatesCountPost200Response();
            CertificateAPIResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('data')) {
                obj['data'] = CertificateCertCount.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = ApiClient.convertToType(data['pagination'], Object);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1CertificatesCountPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1CertificatesCountPost200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          CertificateCertCount.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/CertificateCertCount} data
 */
V1CertificatesCountPost200Response.prototype['data'] = undefined;

/**
 * @member {Object} pagination
 */
V1CertificatesCountPost200Response.prototype['pagination'] = undefined;

/**
 * @member {Boolean} success
 */
V1CertificatesCountPost200Response.prototype['success'] = undefined;


// Implement CertificateAPIResponse interface:
/**
 * @member {Object} data
 */
CertificateAPIResponse.prototype['data'] = undefined;
/**
 * @member {Object} pagination
 */
CertificateAPIResponse.prototype['pagination'] = undefined;
/**
 * @member {Boolean} success
 */
CertificateAPIResponse.prototype['success'] = undefined;




export default V1CertificatesCountPost200Response;

