/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DnsAPIResponse from './DnsAPIResponse';
import DnsSearchPagination from './DnsSearchPagination';
import EshandlerDNS from './EshandlerDNS';

/**
 * The V1DomainSearchPost200Response model module.
 * @module model/V1DomainSearchPost200Response
 * @version 1.0
 */
class V1DomainSearchPost200Response {
    /**
     * Constructs a new <code>V1DomainSearchPost200Response</code>.
     * @alias module:model/V1DomainSearchPost200Response
     * @implements module:model/DnsAPIResponse
     */
    constructor() { 
        DnsAPIResponse.initialize(this);
        V1DomainSearchPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1DomainSearchPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1DomainSearchPost200Response} obj Optional instance to populate.
     * @return {module:model/V1DomainSearchPost200Response} The populated <code>V1DomainSearchPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1DomainSearchPost200Response();
            DnsAPIResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [EshandlerDNS]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = DnsSearchPagination.constructFromObject(data['pagination']);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1DomainSearchPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1DomainSearchPost200Response</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                EshandlerDNS.validateJSON(item);
            };
        }
        // validate the optional field `pagination`
        if (data['pagination']) { // data not null
          DnsSearchPagination.validateJSON(data['pagination']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/EshandlerDNS>} data
 */
V1DomainSearchPost200Response.prototype['data'] = undefined;

/**
 * @member {module:model/DnsSearchPagination} pagination
 */
V1DomainSearchPost200Response.prototype['pagination'] = undefined;

/**
 * @member {Boolean} success
 */
V1DomainSearchPost200Response.prototype['success'] = undefined;


// Implement DnsAPIResponse interface:
/**
 * @member {Object} data
 */
DnsAPIResponse.prototype['data'] = undefined;
/**
 * @member {Object} pagination
 */
DnsAPIResponse.prototype['pagination'] = undefined;
/**
 * @member {Boolean} success
 */
DnsAPIResponse.prototype['success'] = undefined;




export default V1DomainSearchPost200Response;

