/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import APIResponse from './APIResponse';
import CertCount from './CertCount';
import PaginationStruct from './PaginationStruct';

/**
 * The V1HostsCountPost200Response model module.
 * @module model/V1HostsCountPost200Response
 * @version 1.0
 */
class V1HostsCountPost200Response {
    /**
     * Constructs a new <code>V1HostsCountPost200Response</code>.
     * @alias module:model/V1HostsCountPost200Response
     * @implements module:model/APIResponse
     */
    constructor() { 
        APIResponse.initialize(this);
        V1HostsCountPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1HostsCountPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1HostsCountPost200Response} obj Optional instance to populate.
     * @return {module:model/V1HostsCountPost200Response} The populated <code>V1HostsCountPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1HostsCountPost200Response();
            APIResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('data')) {
                obj['data'] = CertCount.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = ApiClient.convertToType(data['pagination'], Object);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty(' meta')) {
                obj[' meta'] = PaginationStruct.constructFromObject(data[' meta']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V1HostsCountPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V1HostsCountPost200Response</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          CertCount.validateJSON(data['data']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field ` meta`
        if (data[' meta']) { // data not null
          PaginationStruct.validateJSON(data[' meta']);
        }

        return true;
    }


}



/**
 * @member {module:model/CertCount} data
 */
V1HostsCountPost200Response.prototype['data'] = undefined;

/**
 * @member {String} message
 */
V1HostsCountPost200Response.prototype['message'] = undefined;

/**
 * @member {Object} pagination
 */
V1HostsCountPost200Response.prototype['pagination'] = undefined;

/**
 * @member {Boolean} success
 */
V1HostsCountPost200Response.prototype['success'] = undefined;

/**
 * @member {module:model/PaginationStruct}  meta
 */
V1HostsCountPost200Response.prototype[' meta'] = undefined;


// Implement APIResponse interface:
/**
 * @member {Object} data
 */
APIResponse.prototype['data'] = undefined;
/**
 * @member {String} message
 */
APIResponse.prototype['message'] = undefined;
/**
 * @member {Object} pagination
 */
APIResponse.prototype['pagination'] = undefined;
/**
 * @member {Boolean} success
 */
APIResponse.prototype['success'] = undefined;




export default V1HostsCountPost200Response;

