/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CybleComOdinApiControllersV2IpservicesAPIResponse from './CybleComOdinApiControllersV2IpservicesAPIResponse';
import CybleComOdinApiControllersV2IpservicesSearchPagination from './CybleComOdinApiControllersV2IpservicesSearchPagination';
import ServiceService from './ServiceService';

/**
 * The V2HostsSearchPost200Response model module.
 * @module model/V2HostsSearchPost200Response
 * @version 1.0
 */
class V2HostsSearchPost200Response {
    /**
     * Constructs a new <code>V2HostsSearchPost200Response</code>.
     * @alias module:model/V2HostsSearchPost200Response
     * @implements module:model/CybleComOdinApiControllersV2IpservicesAPIResponse
     */
    constructor() { 
        CybleComOdinApiControllersV2IpservicesAPIResponse.initialize(this);
        V2HostsSearchPost200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V2HostsSearchPost200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V2HostsSearchPost200Response} obj Optional instance to populate.
     * @return {module:model/V2HostsSearchPost200Response} The populated <code>V2HostsSearchPost200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V2HostsSearchPost200Response();
            CybleComOdinApiControllersV2IpservicesAPIResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ServiceService]);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = ApiClient.convertToType(data['pagination'], Object);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty(' pagination')) {
                obj[' pagination'] = CybleComOdinApiControllersV2IpservicesSearchPagination.constructFromObject(data[' pagination']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>V2HostsSearchPost200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>V2HostsSearchPost200Response</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                ServiceService.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field ` pagination`
        if (data[' pagination']) { // data not null
          CybleComOdinApiControllersV2IpservicesSearchPagination.validateJSON(data[' pagination']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ServiceService>} data
 */
V2HostsSearchPost200Response.prototype['data'] = undefined;

/**
 * @member {String} message
 */
V2HostsSearchPost200Response.prototype['message'] = undefined;

/**
 * @member {Object} pagination
 */
V2HostsSearchPost200Response.prototype['pagination'] = undefined;

/**
 * @member {Boolean} success
 */
V2HostsSearchPost200Response.prototype['success'] = undefined;

/**
 * @member {module:model/CybleComOdinApiControllersV2IpservicesSearchPagination}  pagination
 */
V2HostsSearchPost200Response.prototype[' pagination'] = undefined;


// Implement CybleComOdinApiControllersV2IpservicesAPIResponse interface:
/**
 * @member {Object} data
 */
CybleComOdinApiControllersV2IpservicesAPIResponse.prototype['data'] = undefined;
/**
 * @member {String} message
 */
CybleComOdinApiControllersV2IpservicesAPIResponse.prototype['message'] = undefined;
/**
 * @member {Object} pagination
 */
CybleComOdinApiControllersV2IpservicesAPIResponse.prototype['pagination'] = undefined;
/**
 * @member {Boolean} success
 */
CybleComOdinApiControllersV2IpservicesAPIResponse.prototype['success'] = undefined;




export default V2HostsSearchPost200Response;

