/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateSubject model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateSubject
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateSubject {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSubject</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateSubject
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateSubject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateSubject} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateSubject} The populated <code>CertificateCertificateHashResponseDataCertificateSubject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateSubject();
      if (data.hasOwnProperty('common_name'))
        obj.commonName = ApiClient.convertToType(data['common_name'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} commonName
 */
CertificateCertificateHashResponseDataCertificateSubject.prototype.commonName = undefined;

