/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateCertSummaryRequest model module.
 * @module odin/models/CertificateCertSummaryRequest
 * @version 1.0
 */
export default class CertificateCertSummaryRequest {
  /**
   * Constructs a new <code>CertificateCertSummaryRequest</code>.
   * @alias module:odin/models/CertificateCertSummaryRequest
   * @class
   * @param field {String} 
   * @param limit {Number} 
   */
  constructor(field, limit) {
    this.field = field;
    this.limit = limit;
  }

  /**
   * Constructs a <code>CertificateCertSummaryRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertSummaryRequest} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertSummaryRequest} The populated <code>CertificateCertSummaryRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertSummaryRequest();
      if (data.hasOwnProperty('field'))
        obj.field = ApiClient.convertToType(data['field'], 'String');
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('query'))
        obj.query = ApiClient.convertToType(data['query'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} field
 */
CertificateCertSummaryRequest.prototype.field = undefined;

/**
 * @member {Number} limit
 */
CertificateCertSummaryRequest.prototype.limit = undefined;

/**
 * @member {String} query
 */
CertificateCertSummaryRequest.prototype.query = undefined;

