/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm from './CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm';

/**
 * The CertificateCertificateHashResponseDataCertificateSignature model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateSignature
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateSignature {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSignature</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateSignature
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateSignature</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateSignature} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateSignature} The populated <code>CertificateCertificateHashResponseDataCertificateSignature</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateSignature();
      if (data.hasOwnProperty('signature_algorithm'))
        obj.signatureAlgorithm = CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm.constructFromObject(data['signature_algorithm']);
    }
    return obj;
  }
}

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateSignatureSignatureAlgorithm} signatureAlgorithm
 */
CertificateCertificateHashResponseDataCertificateSignature.prototype.signatureAlgorithm = undefined;

