/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames from './CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames';

/**
 * The CertificateCertificateHashResponseDataCertificateSubjectAltName model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltName
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateSubjectAltName {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSubjectAltName</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltName
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateSubjectAltName</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltName} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltName} The populated <code>CertificateCertificateHashResponseDataCertificateSubjectAltName</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateSubjectAltName();
      if (data.hasOwnProperty('dns_names'))
        obj.dnsNames = ApiClient.convertToType(data['dns_names'], ['String']);
      if (data.hasOwnProperty('extended_dns_names'))
        obj.extendedDnsNames = ApiClient.convertToType(data['extended_dns_names'], [CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames]);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} dnsNames
 */
CertificateCertificateHashResponseDataCertificateSubjectAltName.prototype.dnsNames = undefined;

/**
 * @member {Array.<module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames>} extendedDnsNames
 */
CertificateCertificateHashResponseDataCertificateSubjectAltName.prototype.extendedDnsNames = undefined;

