/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName from './CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName';
import CertificateCertificateHashResponseDataCertificateIssuer from './CertificateCertificateHashResponseDataCertificateIssuer';
import CertificateCertificateHashResponseDataCertificateSubject from './CertificateCertificateHashResponseDataCertificateSubject';
import CertificateCertificateHashResponseDataCertificateValidity from './CertificateCertificateHashResponseDataCertificateValidity';

/**
 * The CertificateCertificateSearchData model module.
 * @module odin/models/CertificateCertificateSearchData
 * @version 1.0
 */
export default class CertificateCertificateSearchData {
  /**
   * Constructs a new <code>CertificateCertificateSearchData</code>.
   * @alias module:odin/models/CertificateCertificateSearchData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateSearchData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateSearchData} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateSearchData} The populated <code>CertificateCertificateSearchData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateSearchData();
      if (data.hasOwnProperty('fingerprint_md5'))
        obj.fingerprintMd5 = ApiClient.convertToType(data['fingerprint_md5'], 'String');
      if (data.hasOwnProperty('fingerprint_sha1'))
        obj.fingerprintSha1 = ApiClient.convertToType(data['fingerprint_sha1'], 'String');
      if (data.hasOwnProperty('fingerprint_sha256'))
        obj.fingerprintSha256 = ApiClient.convertToType(data['fingerprint_sha256'], 'String');
      if (data.hasOwnProperty('issuer'))
        obj.issuer = CertificateCertificateHashResponseDataCertificateIssuer.constructFromObject(data['issuer']);
      if (data.hasOwnProperty('subject'))
        obj.subject = CertificateCertificateHashResponseDataCertificateSubject.constructFromObject(data['subject']);
      if (data.hasOwnProperty('subject_alt_name'))
        obj.subjectAltName = CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName.constructFromObject(data['subject_alt_name']);
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('validity'))
        obj.validity = CertificateCertificateHashResponseDataCertificateValidity.constructFromObject(data['validity']);
    }
    return obj;
  }
}

/**
 * @member {String} fingerprintMd5
 */
CertificateCertificateSearchData.prototype.fingerprintMd5 = undefined;

/**
 * @member {String} fingerprintSha1
 */
CertificateCertificateSearchData.prototype.fingerprintSha1 = undefined;

/**
 * @member {String} fingerprintSha256
 */
CertificateCertificateSearchData.prototype.fingerprintSha256 = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateIssuer} issuer
 */
CertificateCertificateSearchData.prototype.issuer = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateSubject} subject
 */
CertificateCertificateSearchData.prototype.subject = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName} subjectAltName
 */
CertificateCertificateSearchData.prototype.subjectAltName = undefined;

/**
 * @member {Array.<String>} tags
 */
CertificateCertificateSearchData.prototype.tags = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateValidity} validity
 */
CertificateCertificateSearchData.prototype.validity = undefined;

