/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateIssuer model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateIssuer
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateIssuer {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateIssuer</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateIssuer
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateIssuer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateIssuer} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateIssuer} The populated <code>CertificateCertificateHashResponseDataCertificateIssuer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateIssuer();
      if (data.hasOwnProperty('common_name'))
        obj.commonName = ApiClient.convertToType(data['common_name'], ['String']);
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], ['String']);
      if (data.hasOwnProperty('organization'))
        obj.organization = ApiClient.convertToType(data['organization'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} commonName
 */
CertificateCertificateHashResponseDataCertificateIssuer.prototype.commonName = undefined;

/**
 * @member {Array.<String>} country
 */
CertificateCertificateHashResponseDataCertificateIssuer.prototype.country = undefined;

/**
 * @member {Array.<String>} organization
 */
CertificateCertificateHashResponseDataCertificateIssuer.prototype.organization = undefined;

