/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints} The populated <code>CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints();
      if (data.hasOwnProperty('is_ca'))
        obj.isCa = ApiClient.convertToType(data['is_ca'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} isCa
 */
CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints.prototype.isCa = undefined;

