/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey from './CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey';

/**
 * The CertificateCertificateHashResponseDataCertificateSubjectKeyInfo model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfo
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateSubjectKeyInfo {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSubjectKeyInfo</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateSubjectKeyInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfo} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfo} The populated <code>CertificateCertificateHashResponseDataCertificateSubjectKeyInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateSubjectKeyInfo();
      if (data.hasOwnProperty('fingerprint_sha256'))
        obj.fingerprintSha256 = ApiClient.convertToType(data['fingerprint_sha256'], 'String');
      if (data.hasOwnProperty('key_algorithm'))
        obj.keyAlgorithm = ApiClient.convertToType(data['key_algorithm'], 'String');
      if (data.hasOwnProperty('public_key'))
        obj.publicKey = CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.constructFromObject(data['public_key']);
    }
    return obj;
  }
}

/**
 * @member {String} fingerprintSha256
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfo.prototype.fingerprintSha256 = undefined;

/**
 * @member {String} keyAlgorithm
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfo.prototype.keyAlgorithm = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey} publicKey
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfo.prototype.publicKey = undefined;

