/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateSummaryResponseDataBuckets model module.
 * @module odin/models/CertificateCertificateSummaryResponseDataBuckets
 * @version 1.0
 */
export default class CertificateCertificateSummaryResponseDataBuckets {
  /**
   * Constructs a new <code>CertificateCertificateSummaryResponseDataBuckets</code>.
   * @alias module:odin/models/CertificateCertificateSummaryResponseDataBuckets
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateSummaryResponseDataBuckets</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateSummaryResponseDataBuckets} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateSummaryResponseDataBuckets} The populated <code>CertificateCertificateSummaryResponseDataBuckets</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateSummaryResponseDataBuckets();
      if (data.hasOwnProperty('doc_count'))
        obj.docCount = ApiClient.convertToType(data['doc_count'], 'Number');
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} docCount
 */
CertificateCertificateSummaryResponseDataBuckets.prototype.docCount = undefined;

/**
 * @member {String} key
 */
CertificateCertificateSummaryResponseDataBuckets.prototype.key = undefined;

