/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateAPIResponse model module.
 * @module odin/models/CertificateAPIResponse
 * @version 1.0
 */
export default class CertificateAPIResponse {
  /**
   * Constructs a new <code>CertificateAPIResponse</code>.
   * @alias module:odin/models/CertificateAPIResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateAPIResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateAPIResponse} obj Optional instance to populate.
   * @return {module:odin/models/CertificateAPIResponse} The populated <code>CertificateAPIResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateAPIResponse();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
      if (data.hasOwnProperty('pagination'))
        obj.pagination = ApiClient.convertToType(data['pagination'], Object);
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Object} data
 */
CertificateAPIResponse.prototype.data = undefined;

/**
 * @member {Object} pagination
 */
CertificateAPIResponse.prototype.pagination = undefined;

/**
 * @member {Boolean} success
 */
CertificateAPIResponse.prototype.success = undefined;

