/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames} The populated <code>CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames();
      if (data.hasOwnProperty('domain'))
        obj.domain = ApiClient.convertToType(data['domain'], 'String');
      if (data.hasOwnProperty('fld'))
        obj.fld = ApiClient.convertToType(data['fld'], 'String');
      if (data.hasOwnProperty('subdomain'))
        obj.subdomain = ApiClient.convertToType(data['subdomain'], 'String');
      if (data.hasOwnProperty('tld'))
        obj.tld = ApiClient.convertToType(data['tld'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} domain
 */
CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames.prototype.domain = undefined;

/**
 * @member {String} fld
 */
CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames.prototype.fld = undefined;

/**
 * @member {String} subdomain
 */
CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames.prototype.subdomain = undefined;

/**
 * @member {String} tld
 */
CertificateCertificateHashResponseDataCertificateSubjectAltNameExtendedDnsNames.prototype.tld = undefined;

