/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CertificateCertificateSummaryResponseData from './CertificateCertificateSummaryResponseData';

/**
 * The CertificateCertificateSummaryResponse model module.
 * @module odin/models/CertificateCertificateSummaryResponse
 * @version 1.0
 */
export default class CertificateCertificateSummaryResponse {
  /**
   * Constructs a new <code>CertificateCertificateSummaryResponse</code>.
   * @alias module:odin/models/CertificateCertificateSummaryResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateSummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateSummaryResponse} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateSummaryResponse} The populated <code>CertificateCertificateSummaryResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateSummaryResponse();
      if (data.hasOwnProperty('data'))
        obj.data = CertificateCertificateSummaryResponseData.constructFromObject(data['data']);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:odin/models/CertificateCertificateSummaryResponseData} data
 */
CertificateCertificateSummaryResponse.prototype.data = undefined;

/**
 * @member {String} message
 */
CertificateCertificateSummaryResponse.prototype.message = undefined;

/**
 * @member {Boolean} success
 */
CertificateCertificateSummaryResponse.prototype.success = undefined;

