/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName} The populated <code>CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName();
      if (data.hasOwnProperty('dns_names'))
        obj.dnsNames = ApiClient.convertToType(data['dns_names'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} dnsNames
 */
CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName.prototype.dnsNames = undefined;

