/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CertificateCertificateHashResponseDataCertificateExtensionsAuthorityInfoAccess from './CertificateCertificateHashResponseDataCertificateExtensionsAuthorityInfoAccess';
import CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints from './CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints';
import CertificateCertificateHashResponseDataCertificateExtensionsCertificatePolicies from './CertificateCertificateHashResponseDataCertificateExtensionsCertificatePolicies';
import CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage from './CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage';
import CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage from './CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage';
import CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName from './CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName';

/**
 * The CertificateCertificateHashResponseDataCertificateExtensions model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateExtensions
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateExtensions {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateExtensions</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateExtensions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateExtensions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensions} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensions} The populated <code>CertificateCertificateHashResponseDataCertificateExtensions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateExtensions();
      if (data.hasOwnProperty('authority_info_access'))
        obj.authorityInfoAccess = CertificateCertificateHashResponseDataCertificateExtensionsAuthorityInfoAccess.constructFromObject(data['authority_info_access']);
      if (data.hasOwnProperty('authority_key_id'))
        obj.authorityKeyId = ApiClient.convertToType(data['authority_key_id'], 'String');
      if (data.hasOwnProperty('basic_constraints'))
        obj.basicConstraints = CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints.constructFromObject(data['basic_constraints']);
      if (data.hasOwnProperty('certificate_policies'))
        obj.certificatePolicies = ApiClient.convertToType(data['certificate_policies'], [CertificateCertificateHashResponseDataCertificateExtensionsCertificatePolicies]);
      if (data.hasOwnProperty('ct_poison'))
        obj.ctPoison = ApiClient.convertToType(data['ct_poison'], 'Boolean');
      if (data.hasOwnProperty('extended_key_usage'))
        obj.extendedKeyUsage = CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage.constructFromObject(data['extended_key_usage']);
      if (data.hasOwnProperty('key_usage'))
        obj.keyUsage = CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage.constructFromObject(data['key_usage']);
      if (data.hasOwnProperty('subject_alt_name'))
        obj.subjectAltName = CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName.constructFromObject(data['subject_alt_name']);
      if (data.hasOwnProperty('subject_key_id'))
        obj.subjectKeyId = ApiClient.convertToType(data['subject_key_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsAuthorityInfoAccess} authorityInfoAccess
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.authorityInfoAccess = undefined;

/**
 * @member {String} authorityKeyId
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.authorityKeyId = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsBasicConstraints} basicConstraints
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.basicConstraints = undefined;

/**
 * @member {Array.<module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsCertificatePolicies>} certificatePolicies
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.certificatePolicies = undefined;

/**
 * @member {Boolean} ctPoison
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.ctPoison = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsExtendedKeyUsage} extendedKeyUsage
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.extendedKeyUsage = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsKeyUsage} keyUsage
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.keyUsage = undefined;

/**
 * @member {module:odin/models/CertificateCertificateHashResponseDataCertificateExtensionsSubjectAltName} subjectAltName
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.subjectAltName = undefined;

/**
 * @member {String} subjectKeyId
 */
CertificateCertificateHashResponseDataCertificateExtensions.prototype.subjectKeyId = undefined;

