/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey model module.
 * @module odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey
 * @version 1.0
 */
export default class CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey {
  /**
   * Constructs a new <code>CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey</code>.
   * @alias module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey} obj Optional instance to populate.
   * @return {module:odin/models/CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey} The populated <code>CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey();
      if (data.hasOwnProperty('b'))
        obj.b = ApiClient.convertToType(data['b'], 'String');
      if (data.hasOwnProperty('curve'))
        obj.curve = ApiClient.convertToType(data['curve'], 'String');
      if (data.hasOwnProperty('gx'))
        obj.gx = ApiClient.convertToType(data['gx'], 'String');
      if (data.hasOwnProperty('gy'))
        obj.gy = ApiClient.convertToType(data['gy'], 'String');
      if (data.hasOwnProperty('length'))
        obj.length = ApiClient.convertToType(data['length'], 'Number');
      if (data.hasOwnProperty('p'))
        obj.p = ApiClient.convertToType(data['p'], 'String');
      if (data.hasOwnProperty('x'))
        obj.x = ApiClient.convertToType(data['x'], 'String');
      if (data.hasOwnProperty('y'))
        obj.y = ApiClient.convertToType(data['y'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} b
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.prototype.b = undefined;

/**
 * @member {String} curve
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.prototype.curve = undefined;

/**
 * @member {String} gx
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.prototype.gx = undefined;

/**
 * @member {String} gy
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.prototype.gy = undefined;

/**
 * @member {Number} length
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.prototype.length = undefined;

/**
 * @member {String} p
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.prototype.p = undefined;

/**
 * @member {String} x
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.prototype.x = undefined;

/**
 * @member {String} y
 */
CertificateCertificateHashResponseDataCertificateSubjectKeyInfoPublicKey.prototype.y = undefined;

