/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ExposedSearchRequest model module.
 * @module odin/models/ExposedSearchRequest
 * @version 1.0
 */
export default class ExposedSearchRequest {
  /**
   * Constructs a new <code>ExposedSearchRequest</code>.
   * @alias module:odin/models/ExposedSearchRequest
   * @class
   * @param limit {Number} 
   */
  constructor(limit) {
    this.limit = limit;
  }

  /**
   * Constructs a <code>ExposedSearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/ExposedSearchRequest} obj Optional instance to populate.
   * @return {module:odin/models/ExposedSearchRequest} The populated <code>ExposedSearchRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExposedSearchRequest();
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('query'))
        obj.query = ApiClient.convertToType(data['query'], 'String');
      if (data.hasOwnProperty('sort_by'))
        obj.sortBy = ApiClient.convertToType(data['sort_by'], 'String');
      if (data.hasOwnProperty('sort_dir'))
        obj.sortDir = ApiClient.convertToType(data['sort_dir'], 'String');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], [Object]);
    }
    return obj;
  }
}

/**
 * @member {Number} limit
 */
ExposedSearchRequest.prototype.limit = undefined;

/**
 * @member {String} query
 */
ExposedSearchRequest.prototype.query = undefined;

/**
 * @member {String} sortBy
 */
ExposedSearchRequest.prototype.sortBy = undefined;

/**
 * @member {String} sortDir
 */
ExposedSearchRequest.prototype.sortDir = undefined;

/**
 * @member {Array.<Object>} start
 */
ExposedSearchRequest.prototype.start = undefined;

