/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ExposedBucket model module.
 * @module odin/models/ExposedBucket
 * @version 1.0
 */
export default class ExposedBucket {
  /**
   * Constructs a new <code>ExposedBucket</code>.
   * @alias module:odin/models/ExposedBucket
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ExposedBucket</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/ExposedBucket} obj Optional instance to populate.
   * @return {module:odin/models/ExposedBucket} The populated <code>ExposedBucket</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExposedBucket();
      if (data.hasOwnProperty('age_in_days'))
        obj.ageInDays = ApiClient.convertToType(data['age_in_days'], 'Number');
      if (data.hasOwnProperty('categories'))
        obj.categories = ApiClient.convertToType(data['categories'], ['String']);
      if (data.hasOwnProperty('deleted'))
        obj.deleted = ApiClient.convertToType(data['deleted'], 'Boolean');
      if (data.hasOwnProperty('ef_mod_at'))
        obj.efModAt = ApiClient.convertToType(data['ef_mod_at'], 'String');
      if (data.hasOwnProperty('file_cat_count'))
        obj.fileCatCount = ApiClient.convertToType(data['file_cat_count'], {'String': 'Number'});
      if (data.hasOwnProperty('files'))
        obj.files = ApiClient.convertToType(data['files'], 'Number');
      if (data.hasOwnProperty('ins_at'))
        obj.insAt = ApiClient.convertToType(data['ins_at'], 'String');
      if (data.hasOwnProperty('labels'))
        obj.labels = ApiClient.convertToType(data['labels'], ['String']);
      if (data.hasOwnProperty('last_found_at'))
        obj.lastFoundAt = ApiClient.convertToType(data['last_found_at'], 'String');
      if (data.hasOwnProperty('last_open_at'))
        obj.lastOpenAt = ApiClient.convertToType(data['last_open_at'], 'String');
      if (data.hasOwnProperty('lf_mod_at'))
        obj.lfModAt = ApiClient.convertToType(data['lf_mod_at'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('new_files'))
        obj.newFiles = ApiClient.convertToType(data['new_files'], 'Number');
      if (data.hasOwnProperty('open'))
        obj.open = ApiClient.convertToType(data['open'], 'Boolean');
      if (data.hasOwnProperty('owner_id'))
        obj.ownerId = ApiClient.convertToType(data['owner_id'], 'String');
      if (data.hasOwnProperty('prev_scan_at'))
        obj.prevScanAt = ApiClient.convertToType(data['prev_scan_at'], 'String');
      if (data.hasOwnProperty('provider'))
        obj.provider = ApiClient.convertToType(data['provider'], 'String');
      if (data.hasOwnProperty('region'))
        obj.region = ApiClient.convertToType(data['region'], 'String');
      if (data.hasOwnProperty('scan_at'))
        obj.scanAt = ApiClient.convertToType(data['scan_at'], 'String');
      if (data.hasOwnProperty('sensitive_files'))
        obj.sensitiveFiles = ApiClient.convertToType(data['sensitive_files'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} ageInDays
 */
ExposedBucket.prototype.ageInDays = undefined;

/**
 * @member {Array.<String>} categories
 */
ExposedBucket.prototype.categories = undefined;

/**
 * @member {Boolean} deleted
 */
ExposedBucket.prototype.deleted = undefined;

/**
 * @member {String} efModAt
 */
ExposedBucket.prototype.efModAt = undefined;

/**
 * @member {Object.<String, Number>} fileCatCount
 */
ExposedBucket.prototype.fileCatCount = undefined;

/**
 * @member {Number} files
 */
ExposedBucket.prototype.files = undefined;

/**
 * @member {String} insAt
 */
ExposedBucket.prototype.insAt = undefined;

/**
 * @member {Array.<String>} labels
 */
ExposedBucket.prototype.labels = undefined;

/**
 * @member {String} lastFoundAt
 */
ExposedBucket.prototype.lastFoundAt = undefined;

/**
 * @member {String} lastOpenAt
 */
ExposedBucket.prototype.lastOpenAt = undefined;

/**
 * @member {String} lfModAt
 */
ExposedBucket.prototype.lfModAt = undefined;

/**
 * @member {String} name
 */
ExposedBucket.prototype.name = undefined;

/**
 * @member {Number} newFiles
 */
ExposedBucket.prototype.newFiles = undefined;

/**
 * @member {Boolean} open
 */
ExposedBucket.prototype.open = undefined;

/**
 * @member {String} ownerId
 */
ExposedBucket.prototype.ownerId = undefined;

/**
 * @member {String} prevScanAt
 */
ExposedBucket.prototype.prevScanAt = undefined;

/**
 * @member {String} provider
 */
ExposedBucket.prototype.provider = undefined;

/**
 * @member {String} region
 */
ExposedBucket.prototype.region = undefined;

/**
 * @member {String} scanAt
 */
ExposedBucket.prototype.scanAt = undefined;

/**
 * @member {Number} sensitiveFiles
 */
ExposedBucket.prototype.sensitiveFiles = undefined;

