/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ExposedFile model module.
 * @module odin/models/ExposedFile
 * @version 1.0
 */
export default class ExposedFile {
  /**
   * Constructs a new <code>ExposedFile</code>.
   * @alias module:odin/models/ExposedFile
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ExposedFile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/ExposedFile} obj Optional instance to populate.
   * @return {module:odin/models/ExposedFile} The populated <code>ExposedFile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExposedFile();
      if (data.hasOwnProperty('accessible'))
        obj.accessible = ApiClient.convertToType(data['accessible'], 'Boolean');
      if (data.hasOwnProperty('bucket'))
        obj.bucket = ApiClient.convertToType(data['bucket'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('etag'))
        obj.etag = ApiClient.convertToType(data['etag'], 'String');
      if (data.hasOwnProperty('ext'))
        obj.ext = ApiClient.convertToType(data['ext'], 'String');
      if (data.hasOwnProperty('ext_desc'))
        obj.extDesc = ApiClient.convertToType(data['ext_desc'], 'String');
      if (data.hasOwnProperty('ins_at'))
        obj.insAt = ApiClient.convertToType(data['ins_at'], 'String');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('mod_at'))
        obj.modAt = ApiClient.convertToType(data['mod_at'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('path'))
        obj.path = ApiClient.convertToType(data['path'], 'String');
      if (data.hasOwnProperty('provider'))
        obj.provider = ApiClient.convertToType(data['provider'], 'String');
      if (data.hasOwnProperty('region'))
        obj.region = ApiClient.convertToType(data['region'], 'String');
      if (data.hasOwnProperty('scan_at'))
        obj.scanAt = ApiClient.convertToType(data['scan_at'], 'String');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'Number');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} accessible
 */
ExposedFile.prototype.accessible = undefined;

/**
 * @member {String} bucket
 */
ExposedFile.prototype.bucket = undefined;

/**
 * @member {String} category
 */
ExposedFile.prototype.category = undefined;

/**
 * @member {String} etag
 */
ExposedFile.prototype.etag = undefined;

/**
 * @member {String} ext
 */
ExposedFile.prototype.ext = undefined;

/**
 * @member {String} extDesc
 */
ExposedFile.prototype.extDesc = undefined;

/**
 * @member {String} insAt
 */
ExposedFile.prototype.insAt = undefined;

/**
 * @member {String} label
 */
ExposedFile.prototype.label = undefined;

/**
 * @member {String} modAt
 */
ExposedFile.prototype.modAt = undefined;

/**
 * @member {String} name
 */
ExposedFile.prototype.name = undefined;

/**
 * @member {String} path
 */
ExposedFile.prototype.path = undefined;

/**
 * @member {String} provider
 */
ExposedFile.prototype.provider = undefined;

/**
 * @member {String} region
 */
ExposedFile.prototype.region = undefined;

/**
 * @member {String} scanAt
 */
ExposedFile.prototype.scanAt = undefined;

/**
 * @member {Number} size
 */
ExposedFile.prototype.size = undefined;

/**
 * @member {String} type
 */
ExposedFile.prototype.type = undefined;

/**
 * @member {String} url
 */
ExposedFile.prototype.url = undefined;

