/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ExposedFile from './ExposedFile';
import ExposedSearchPagination from './ExposedSearchPagination';

/**
 * The ExposedFileAPIResponse model module.
 * @module odin/models/ExposedFileAPIResponse
 * @version 1.0
 */
export default class ExposedFileAPIResponse {
  /**
   * Constructs a new <code>ExposedFileAPIResponse</code>.
   * @alias module:odin/models/ExposedFileAPIResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ExposedFileAPIResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/ExposedFileAPIResponse} obj Optional instance to populate.
   * @return {module:odin/models/ExposedFileAPIResponse} The populated <code>ExposedFileAPIResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExposedFileAPIResponse();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [ExposedFile]);
      if (data.hasOwnProperty('pagination'))
        obj.pagination = ExposedSearchPagination.constructFromObject(data['pagination']);
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:odin/models/ExposedFile>} data
 */
ExposedFileAPIResponse.prototype.data = undefined;

/**
 * @member {module:odin/models/ExposedSearchPagination} pagination
 */
ExposedFileAPIResponse.prototype.pagination = undefined;

/**
 * @member {Boolean} success
 */
ExposedFileAPIResponse.prototype.success = undefined;

