/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FieldsErrorResponse model module.
 * @module odin/models/FieldsErrorResponse
 * @version 1.0
 */
export default class FieldsErrorResponse {
  /**
   * Constructs a new <code>FieldsErrorResponse</code>.
   * @alias module:odin/models/FieldsErrorResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FieldsErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/FieldsErrorResponse} obj Optional instance to populate.
   * @return {module:odin/models/FieldsErrorResponse} The populated <code>FieldsErrorResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FieldsErrorResponse();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} message
 */
FieldsErrorResponse.prototype.message = undefined;

/**
 * @member {Boolean} success
 */
FieldsErrorResponse.prototype.success = undefined;

