/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CertificateAPIResponse from './CertificateAPIResponse';
import CertificateCertScroll from './CertificateCertScroll';
import CertificateSearchPagination from './CertificateSearchPagination';

/**
 * The InlineResponse2001 model module.
 * @module odin/models/InlineResponse2001
 * @version 1.0
 */
export default class InlineResponse2001 extends CertificateAPIResponse {
  /**
   * Constructs a new <code>InlineResponse2001</code>.
   * @alias module:odin/models/InlineResponse2001
   * @class
   * @extends module:odin/models/CertificateAPIResponse
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/InlineResponse2001} obj Optional instance to populate.
   * @return {module:odin/models/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001();
      CertificateAPIResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = CertificateCertScroll.constructFromObject(data['data']);
      if (data.hasOwnProperty('pagination'))
        obj.pagination = CertificateSearchPagination.constructFromObject(data['pagination']);
    }
    return obj;
  }
}

/**
 * @member {module:odin/models/CertificateCertScroll} data
 */
InlineResponse2001.prototype.data = undefined;

/**
 * @member {module:odin/models/CertificateSearchPagination} pagination
 */
InlineResponse2001.prototype.pagination = undefined;

