/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import IpservicesAPIResponse from './IpservicesAPIResponse';
import IpservicesCertCount from './IpservicesCertCount';
import IpservicesPaginationStruct from './IpservicesPaginationStruct';

/**
 * The InlineResponse2009 model module.
 * @module odin/models/InlineResponse2009
 * @version 1.0
 */
export default class InlineResponse2009 extends IpservicesAPIResponse {
  /**
   * Constructs a new <code>InlineResponse2009</code>.
   * @alias module:odin/models/InlineResponse2009
   * @class
   * @extends module:odin/models/IpservicesAPIResponse
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>InlineResponse2009</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/InlineResponse2009} obj Optional instance to populate.
   * @return {module:odin/models/InlineResponse2009} The populated <code>InlineResponse2009</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2009();
      IpservicesAPIResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty(' meta'))
        obj.meta = IpservicesPaginationStruct.constructFromObject(data[' meta']);
      if (data.hasOwnProperty('data'))
        obj.data = IpservicesCertCount.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:odin/models/IpservicesPaginationStruct} meta
 */
InlineResponse2009.prototype.meta = undefined;

/**
 * @member {module:odin/models/IpservicesCertCount} data
 */
InlineResponse2009.prototype.data = undefined;

