/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import FieldsAPIResponse from './FieldsAPIResponse';
import FieldsField from './FieldsField';

/**
 * The InlineResponse2008 model module.
 * @module odin/models/InlineResponse2008
 * @version 1.0
 */
export default class InlineResponse2008 extends FieldsAPIResponse {
  /**
   * Constructs a new <code>InlineResponse2008</code>.
   * @alias module:odin/models/InlineResponse2008
   * @class
   * @extends module:odin/models/FieldsAPIResponse
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>InlineResponse2008</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/InlineResponse2008} obj Optional instance to populate.
   * @return {module:odin/models/InlineResponse2008} The populated <code>InlineResponse2008</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2008();
      FieldsAPIResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [FieldsField]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:odin/models/FieldsField>} data
 */
InlineResponse2008.prototype.data = undefined;

