/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CertificateAPIResponse from './CertificateAPIResponse';
import CertificateCertScroll from './CertificateCertScroll';

/**
 * The InlineResponse2002 model module.
 * @module odin/models/InlineResponse2002
 * @version 1.0
 */
export default class InlineResponse2002 extends CertificateAPIResponse {
  /**
   * Constructs a new <code>InlineResponse2002</code>.
   * @alias module:odin/models/InlineResponse2002
   * @class
   * @extends module:odin/models/CertificateAPIResponse
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>InlineResponse2002</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/InlineResponse2002} obj Optional instance to populate.
   * @return {module:odin/models/InlineResponse2002} The populated <code>InlineResponse2002</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002();
      CertificateAPIResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = CertificateCertScroll.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:odin/models/CertificateCertScroll} data
 */
InlineResponse2002.prototype.data = undefined;

