/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DnsAPIResponse from './DnsAPIResponse';
import DnsSearchPagination from './DnsSearchPagination';

/**
 * The InlineResponse2003 model module.
 * @module odin/models/InlineResponse2003
 * @version 1.0
 */
export default class InlineResponse2003 extends DnsAPIResponse {
  /**
   * Constructs a new <code>InlineResponse2003</code>.
   * @alias module:odin/models/InlineResponse2003
   * @class
   * @extends module:odin/models/DnsAPIResponse
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>InlineResponse2003</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/InlineResponse2003} obj Optional instance to populate.
   * @return {module:odin/models/InlineResponse2003} The populated <code>InlineResponse2003</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2003();
      DnsAPIResponse.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], ['String']);
      if (data.hasOwnProperty('pagination'))
        obj.pagination = DnsSearchPagination.constructFromObject(data['pagination']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} data
 */
InlineResponse2003.prototype.data = undefined;

/**
 * @member {module:odin/models/DnsSearchPagination} pagination
 */
InlineResponse2003.prototype.pagination = undefined;

