/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import IpservicesHostsSummaryResponseDataBuckets from './IpservicesHostsSummaryResponseDataBuckets';

/**
 * The IpservicesHostsSummaryResponseData model module.
 * @module odin/models/IpservicesHostsSummaryResponseData
 * @version 1.0
 */
export default class IpservicesHostsSummaryResponseData {
  /**
   * Constructs a new <code>IpservicesHostsSummaryResponseData</code>.
   * @alias module:odin/models/IpservicesHostsSummaryResponseData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesHostsSummaryResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesHostsSummaryResponseData} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesHostsSummaryResponseData} The populated <code>IpservicesHostsSummaryResponseData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesHostsSummaryResponseData();
      if (data.hasOwnProperty('buckets'))
        obj.buckets = ApiClient.convertToType(data['buckets'], [IpservicesHostsSummaryResponseDataBuckets]);
      if (data.hasOwnProperty('doc_count_error_upper_bound'))
        obj.docCountErrorUpperBound = ApiClient.convertToType(data['doc_count_error_upper_bound'], 'Number');
      if (data.hasOwnProperty('sum_other_doc_count'))
        obj.sumOtherDocCount = ApiClient.convertToType(data['sum_other_doc_count'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:odin/models/IpservicesHostsSummaryResponseDataBuckets>} buckets
 */
IpservicesHostsSummaryResponseData.prototype.buckets = undefined;

/**
 * @member {Number} docCountErrorUpperBound
 */
IpservicesHostsSummaryResponseData.prototype.docCountErrorUpperBound = undefined;

/**
 * @member {Number} sumOtherDocCount
 */
IpservicesHostsSummaryResponseData.prototype.sumOtherDocCount = undefined;

