/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IpservicesPaginationStruct model module.
 * @module odin/models/IpservicesPaginationStruct
 * @version 1.0
 */
export default class IpservicesPaginationStruct {
  /**
   * Constructs a new <code>IpservicesPaginationStruct</code>.
   * @alias module:odin/models/IpservicesPaginationStruct
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesPaginationStruct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesPaginationStruct} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesPaginationStruct} The populated <code>IpservicesPaginationStruct</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesPaginationStruct();
      if (data.hasOwnProperty('current'))
        obj.current = ApiClient.convertToType(data['current'], 'String');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} current
 */
IpservicesPaginationStruct.prototype.current = undefined;

/**
 * @member {Number} total
 */
IpservicesPaginationStruct.prototype.total = undefined;

