/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IpservicesHostsSearchDataAsn model module.
 * @module odin/models/IpservicesHostsSearchDataAsn
 * @version 1.0
 */
export default class IpservicesHostsSearchDataAsn {
  /**
   * Constructs a new <code>IpservicesHostsSearchDataAsn</code>.
   * @alias module:odin/models/IpservicesHostsSearchDataAsn
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesHostsSearchDataAsn</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesHostsSearchDataAsn} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesHostsSearchDataAsn} The populated <code>IpservicesHostsSearchDataAsn</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesHostsSearchDataAsn();
      if (data.hasOwnProperty('country_code'))
        obj.countryCode = ApiClient.convertToType(data['country_code'], 'String');
      if (data.hasOwnProperty('number'))
        obj._number = ApiClient.convertToType(data['number'], 'String');
      if (data.hasOwnProperty('organization'))
        obj.organization = ApiClient.convertToType(data['organization'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} countryCode
 */
IpservicesHostsSearchDataAsn.prototype.countryCode = undefined;

/**
 * @member {String} _number
 */
IpservicesHostsSearchDataAsn.prototype._number = undefined;

/**
 * @member {String} organization
 */
IpservicesHostsSearchDataAsn.prototype.organization = undefined;

