/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IpservicesHostsIpDetailsResponseDataMeta model module.
 * @module odin/models/IpservicesHostsIpDetailsResponseDataMeta
 * @version 1.0
 */
export default class IpservicesHostsIpDetailsResponseDataMeta {
  /**
   * Constructs a new <code>IpservicesHostsIpDetailsResponseDataMeta</code>.
   * @alias module:odin/models/IpservicesHostsIpDetailsResponseDataMeta
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesHostsIpDetailsResponseDataMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesHostsIpDetailsResponseDataMeta} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesHostsIpDetailsResponseDataMeta} The populated <code>IpservicesHostsIpDetailsResponseDataMeta</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesHostsIpDetailsResponseDataMeta();
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('desc'))
        obj.desc = ApiClient.convertToType(data['desc'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} category
 */
IpservicesHostsIpDetailsResponseDataMeta.prototype.category = undefined;

/**
 * @member {String} desc
 */
IpservicesHostsIpDetailsResponseDataMeta.prototype.desc = undefined;

/**
 * @member {String} name
 */
IpservicesHostsIpDetailsResponseDataMeta.prototype.name = undefined;

/**
 * @member {Object} tags
 */
IpservicesHostsIpDetailsResponseDataMeta.prototype.tags = undefined;

