/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IpservicesSearchPagination model module.
 * @module odin/models/IpservicesSearchPagination
 * @version 1.0
 */
export default class IpservicesSearchPagination {
  /**
   * Constructs a new <code>IpservicesSearchPagination</code>.
   * @alias module:odin/models/IpservicesSearchPagination
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesSearchPagination</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesSearchPagination} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesSearchPagination} The populated <code>IpservicesSearchPagination</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesSearchPagination();
      if (data.hasOwnProperty('last'))
        obj.last = ApiClient.convertToType(data['last'], ['Number']);
      if (data.hasOwnProperty('limit'))
        obj.limit = ApiClient.convertToType(data['limit'], 'Number');
      if (data.hasOwnProperty('start'))
        obj.start = ApiClient.convertToType(data['start'], ['Number']);
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<Number>} last
 */
IpservicesSearchPagination.prototype.last = undefined;

/**
 * @member {Number} limit
 */
IpservicesSearchPagination.prototype.limit = undefined;

/**
 * @member {Array.<Number>} start
 */
IpservicesSearchPagination.prototype.start = undefined;

/**
 * @member {Number} total
 */
IpservicesSearchPagination.prototype.total = undefined;

