/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import IpservicesHostsIpDetailsResponseDataLocationCoordinates from './IpservicesHostsIpDetailsResponseDataLocationCoordinates';

/**
 * The IpservicesHostsIpDetailsResponseDataLocation model module.
 * @module odin/models/IpservicesHostsIpDetailsResponseDataLocation
 * @version 1.0
 */
export default class IpservicesHostsIpDetailsResponseDataLocation {
  /**
   * Constructs a new <code>IpservicesHostsIpDetailsResponseDataLocation</code>.
   * @alias module:odin/models/IpservicesHostsIpDetailsResponseDataLocation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesHostsIpDetailsResponseDataLocation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesHostsIpDetailsResponseDataLocation} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesHostsIpDetailsResponseDataLocation} The populated <code>IpservicesHostsIpDetailsResponseDataLocation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesHostsIpDetailsResponseDataLocation();
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('continent'))
        obj.continent = ApiClient.convertToType(data['continent'], 'String');
      if (data.hasOwnProperty('coordinates'))
        obj.coordinates = IpservicesHostsIpDetailsResponseDataLocationCoordinates.constructFromObject(data['coordinates']);
      if (data.hasOwnProperty('country_code'))
        obj.countryCode = ApiClient.convertToType(data['country_code'], 'String');
      if (data.hasOwnProperty('country_name'))
        obj.countryName = ApiClient.convertToType(data['country_name'], 'String');
      if (data.hasOwnProperty('geo_point'))
        obj.geoPoint = ApiClient.convertToType(data['geo_point'], 'String');
      if (data.hasOwnProperty('locale_code'))
        obj.localeCode = ApiClient.convertToType(data['locale_code'], 'String');
      if (data.hasOwnProperty('network'))
        obj.network = ApiClient.convertToType(data['network'], 'String');
      if (data.hasOwnProperty('postal_code'))
        obj.postalCode = ApiClient.convertToType(data['postal_code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} city
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.city = undefined;

/**
 * @member {String} continent
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.continent = undefined;

/**
 * @member {module:odin/models/IpservicesHostsIpDetailsResponseDataLocationCoordinates} coordinates
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.coordinates = undefined;

/**
 * @member {String} countryCode
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.countryCode = undefined;

/**
 * @member {String} countryName
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.countryName = undefined;

/**
 * @member {String} geoPoint
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.geoPoint = undefined;

/**
 * @member {String} localeCode
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.localeCode = undefined;

/**
 * @member {String} network
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.network = undefined;

/**
 * @member {String} postalCode
 */
IpservicesHostsIpDetailsResponseDataLocation.prototype.postalCode = undefined;

