/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import IpservicesHostsIpDetailsResponseDataAsn from './IpservicesHostsIpDetailsResponseDataAsn';
import IpservicesHostsIpDetailsResponseDataHostnames from './IpservicesHostsIpDetailsResponseDataHostnames';
import IpservicesHostsIpDetailsResponseDataLocation from './IpservicesHostsIpDetailsResponseDataLocation';
import IpservicesHostsIpDetailsResponseDataServices from './IpservicesHostsIpDetailsResponseDataServices';
import IpservicesHostsIpDetailsResponseDataTags from './IpservicesHostsIpDetailsResponseDataTags';
import IpservicesHostsIpDetailsResponseDataWhois from './IpservicesHostsIpDetailsResponseDataWhois';

/**
 * The IpservicesHostsIpDetailsResponseData model module.
 * @module odin/models/IpservicesHostsIpDetailsResponseData
 * @version 1.0
 */
export default class IpservicesHostsIpDetailsResponseData {
  /**
   * Constructs a new <code>IpservicesHostsIpDetailsResponseData</code>.
   * @alias module:odin/models/IpservicesHostsIpDetailsResponseData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesHostsIpDetailsResponseData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesHostsIpDetailsResponseData} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesHostsIpDetailsResponseData} The populated <code>IpservicesHostsIpDetailsResponseData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesHostsIpDetailsResponseData();
      if (data.hasOwnProperty('asn'))
        obj.asn = IpservicesHostsIpDetailsResponseDataAsn.constructFromObject(data['asn']);
      if (data.hasOwnProperty('asn_updated_at'))
        obj.asnUpdatedAt = ApiClient.convertToType(data['asn_updated_at'], 'String');
      if (data.hasOwnProperty('banner'))
        obj.banner = ApiClient.convertToType(data['banner'], ['String']);
      if (data.hasOwnProperty('domains'))
        obj.domains = ApiClient.convertToType(data['domains'], Object);
      if (data.hasOwnProperty('hostnames'))
        obj.hostnames = ApiClient.convertToType(data['hostnames'], [IpservicesHostsIpDetailsResponseDataHostnames]);
      if (data.hasOwnProperty('ip'))
        obj.ip = ApiClient.convertToType(data['ip'], 'String');
      if (data.hasOwnProperty('is_ipv4'))
        obj.isIpv4 = ApiClient.convertToType(data['is_ipv4'], 'Boolean');
      if (data.hasOwnProperty('is_ipv6'))
        obj.isIpv6 = ApiClient.convertToType(data['is_ipv6'], 'Boolean');
      if (data.hasOwnProperty('is_vuln'))
        obj.isVuln = ApiClient.convertToType(data['is_vuln'], 'Boolean');
      if (data.hasOwnProperty('last_updated_at'))
        obj.lastUpdatedAt = ApiClient.convertToType(data['last_updated_at'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = IpservicesHostsIpDetailsResponseDataLocation.constructFromObject(data['location']);
      if (data.hasOwnProperty('location_updated_at'))
        obj.locationUpdatedAt = ApiClient.convertToType(data['location_updated_at'], 'String');
      if (data.hasOwnProperty('scan_id'))
        obj.scanId = ApiClient.convertToType(data['scan_id'], 'Number');
      if (data.hasOwnProperty('services'))
        obj.services = ApiClient.convertToType(data['services'], [IpservicesHostsIpDetailsResponseDataServices]);
      if (data.hasOwnProperty('services_hash'))
        obj.servicesHash = ApiClient.convertToType(data['services_hash'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], [IpservicesHostsIpDetailsResponseDataTags]);
      if (data.hasOwnProperty('whois'))
        obj.whois = IpservicesHostsIpDetailsResponseDataWhois.constructFromObject(data['whois']);
      if (data.hasOwnProperty('whois_updated_at'))
        obj.whoisUpdatedAt = ApiClient.convertToType(data['whois_updated_at'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:odin/models/IpservicesHostsIpDetailsResponseDataAsn} asn
 */
IpservicesHostsIpDetailsResponseData.prototype.asn = undefined;

/**
 * @member {String} asnUpdatedAt
 */
IpservicesHostsIpDetailsResponseData.prototype.asnUpdatedAt = undefined;

/**
 * @member {Array.<String>} banner
 */
IpservicesHostsIpDetailsResponseData.prototype.banner = undefined;

/**
 * @member {Object} domains
 */
IpservicesHostsIpDetailsResponseData.prototype.domains = undefined;

/**
 * @member {Array.<module:odin/models/IpservicesHostsIpDetailsResponseDataHostnames>} hostnames
 */
IpservicesHostsIpDetailsResponseData.prototype.hostnames = undefined;

/**
 * @member {String} ip
 */
IpservicesHostsIpDetailsResponseData.prototype.ip = undefined;

/**
 * @member {Boolean} isIpv4
 */
IpservicesHostsIpDetailsResponseData.prototype.isIpv4 = undefined;

/**
 * @member {Boolean} isIpv6
 */
IpservicesHostsIpDetailsResponseData.prototype.isIpv6 = undefined;

/**
 * @member {Boolean} isVuln
 */
IpservicesHostsIpDetailsResponseData.prototype.isVuln = undefined;

/**
 * @member {String} lastUpdatedAt
 */
IpservicesHostsIpDetailsResponseData.prototype.lastUpdatedAt = undefined;

/**
 * @member {module:odin/models/IpservicesHostsIpDetailsResponseDataLocation} location
 */
IpservicesHostsIpDetailsResponseData.prototype.location = undefined;

/**
 * @member {String} locationUpdatedAt
 */
IpservicesHostsIpDetailsResponseData.prototype.locationUpdatedAt = undefined;

/**
 * @member {Number} scanId
 */
IpservicesHostsIpDetailsResponseData.prototype.scanId = undefined;

/**
 * @member {Array.<module:odin/models/IpservicesHostsIpDetailsResponseDataServices>} services
 */
IpservicesHostsIpDetailsResponseData.prototype.services = undefined;

/**
 * @member {String} servicesHash
 */
IpservicesHostsIpDetailsResponseData.prototype.servicesHash = undefined;

/**
 * @member {Array.<module:odin/models/IpservicesHostsIpDetailsResponseDataTags>} tags
 */
IpservicesHostsIpDetailsResponseData.prototype.tags = undefined;

/**
 * @member {module:odin/models/IpservicesHostsIpDetailsResponseDataWhois} whois
 */
IpservicesHostsIpDetailsResponseData.prototype.whois = undefined;

/**
 * @member {Object} whoisUpdatedAt
 */
IpservicesHostsIpDetailsResponseData.prototype.whoisUpdatedAt = undefined;

