/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import IpservicesIpCveDetails from './IpservicesIpCveDetails';

/**
 * The IpservicesIpCveResponse model module.
 * @module odin/models/IpservicesIpCveResponse
 * @version 1.0
 */
export default class IpservicesIpCveResponse {
  /**
   * Constructs a new <code>IpservicesIpCveResponse</code>.
   * @alias module:odin/models/IpservicesIpCveResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesIpCveResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesIpCveResponse} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesIpCveResponse} The populated <code>IpservicesIpCveResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesIpCveResponse();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], {'String': IpservicesIpCveDetails});
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Object.<String, module:odin/models/IpservicesIpCveDetails>} data
 */
IpservicesIpCveResponse.prototype.data = undefined;

/**
 * @member {String} message
 */
IpservicesIpCveResponse.prototype.message = undefined;

/**
 * @member {Boolean} success
 */
IpservicesIpCveResponse.prototype.success = undefined;

