/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import IpservicesIpCveDetailsExploit from './IpservicesIpCveDetailsExploit';

/**
 * The IpservicesIpCveDetails model module.
 * @module odin/models/IpservicesIpCveDetails
 * @version 1.0
 */
export default class IpservicesIpCveDetails {
  /**
   * Constructs a new <code>IpservicesIpCveDetails</code>.
   * @alias module:odin/models/IpservicesIpCveDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesIpCveDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesIpCveDetails} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesIpCveDetails} The populated <code>IpservicesIpCveDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesIpCveDetails();
      if (data.hasOwnProperty('exploit'))
        obj.exploit = ApiClient.convertToType(data['exploit'], [IpservicesIpCveDetailsExploit]);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('references'))
        obj.references = ApiClient.convertToType(data['references'], ['String']);
      if (data.hasOwnProperty('score'))
        obj.score = ApiClient.convertToType(data['score'], 'Number');
      if (data.hasOwnProperty('services'))
        obj.services = ApiClient.convertToType(data['services'], ['String']);
      if (data.hasOwnProperty('severity'))
        obj.severity = ApiClient.convertToType(data['severity'], 'String');
      if (data.hasOwnProperty('summary'))
        obj.summary = ApiClient.convertToType(data['summary'], 'String');
      if (data.hasOwnProperty('vector_string'))
        obj.vectorString = ApiClient.convertToType(data['vector_string'], 'String');
      if (data.hasOwnProperty('weakness'))
        obj.weakness = ApiClient.convertToType(data['weakness'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:odin/models/IpservicesIpCveDetailsExploit>} exploit
 */
IpservicesIpCveDetails.prototype.exploit = undefined;

/**
 * @member {String} id
 */
IpservicesIpCveDetails.prototype.id = undefined;

/**
 * @member {Array.<String>} references
 */
IpservicesIpCveDetails.prototype.references = undefined;

/**
 * @member {Number} score
 */
IpservicesIpCveDetails.prototype.score = undefined;

/**
 * @member {Array.<String>} services
 */
IpservicesIpCveDetails.prototype.services = undefined;

/**
 * @member {String} severity
 */
IpservicesIpCveDetails.prototype.severity = undefined;

/**
 * @member {String} summary
 */
IpservicesIpCveDetails.prototype.summary = undefined;

/**
 * @member {String} vectorString
 */
IpservicesIpCveDetails.prototype.vectorString = undefined;

/**
 * @member {String} weakness
 */
IpservicesIpCveDetails.prototype.weakness = undefined;

