/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IpservicesHostsIpDetailsResponseDataHostnames model module.
 * @module odin/models/IpservicesHostsIpDetailsResponseDataHostnames
 * @version 1.0
 */
export default class IpservicesHostsIpDetailsResponseDataHostnames {
  /**
   * Constructs a new <code>IpservicesHostsIpDetailsResponseDataHostnames</code>.
   * @alias module:odin/models/IpservicesHostsIpDetailsResponseDataHostnames
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesHostsIpDetailsResponseDataHostnames</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesHostsIpDetailsResponseDataHostnames} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesHostsIpDetailsResponseDataHostnames} The populated <code>IpservicesHostsIpDetailsResponseDataHostnames</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesHostsIpDetailsResponseDataHostnames();
      if (data.hasOwnProperty('last_updated_at'))
        obj.lastUpdatedAt = ApiClient.convertToType(data['last_updated_at'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} lastUpdatedAt
 */
IpservicesHostsIpDetailsResponseDataHostnames.prototype.lastUpdatedAt = undefined;

/**
 * @member {String} name
 */
IpservicesHostsIpDetailsResponseDataHostnames.prototype.name = undefined;

