/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The IpservicesHostsIpDetailsResponseDataWhoisEncoding model module.
 * @module odin/models/IpservicesHostsIpDetailsResponseDataWhoisEncoding
 * @version 1.0
 */
export default class IpservicesHostsIpDetailsResponseDataWhoisEncoding {
  /**
   * Constructs a new <code>IpservicesHostsIpDetailsResponseDataWhoisEncoding</code>.
   * @alias module:odin/models/IpservicesHostsIpDetailsResponseDataWhoisEncoding
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>IpservicesHostsIpDetailsResponseDataWhoisEncoding</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/IpservicesHostsIpDetailsResponseDataWhoisEncoding} obj Optional instance to populate.
   * @return {module:odin/models/IpservicesHostsIpDetailsResponseDataWhoisEncoding} The populated <code>IpservicesHostsIpDetailsResponseDataWhoisEncoding</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new IpservicesHostsIpDetailsResponseDataWhoisEncoding();
      if (data.hasOwnProperty('raw'))
        obj.raw = ApiClient.convertToType(data['raw'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} raw
 */
IpservicesHostsIpDetailsResponseDataWhoisEncoding.prototype.raw = undefined;

