/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TokensUserTokenStats model module.
 * @module odin/models/TokensUserTokenStats
 * @version 1.0
 */
export default class TokensUserTokenStats {
  /**
   * Constructs a new <code>TokensUserTokenStats</code>.
   * @alias module:odin/models/TokensUserTokenStats
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TokensUserTokenStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:odin/models/TokensUserTokenStats} obj Optional instance to populate.
   * @return {module:odin/models/TokensUserTokenStats} The populated <code>TokensUserTokenStats</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TokensUserTokenStats();
      if (data.hasOwnProperty('expires_on'))
        obj.expiresOn = ApiClient.convertToType(data['expires_on'], 'Number');
      if (data.hasOwnProperty('left'))
        obj.left = ApiClient.convertToType(data['left'], 'Number');
      if (data.hasOwnProperty('plan'))
        obj.plan = ApiClient.convertToType(data['plan'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} expiresOn
 */
TokensUserTokenStats.prototype.expiresOn = undefined;

/**
 * @member {Number} left
 */
TokensUserTokenStats.prototype.left = undefined;

/**
 * @member {Number} plan
 */
TokensUserTokenStats.prototype.plan = undefined;

