/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import TokensErrorResponse from '../models/TokensErrorResponse';
import TokensUserTokenStats from '../models/TokensUserTokenStats';

/**
* Credits service.
* @module odin/odin_api/CreditsApi
* @version 1.0
*/
export default class CreditsApi {

    /**
    * Constructs a new CreditsApi. 
    * @alias module:odin/odin_api/CreditsApi
    * @class
    * @param {module:odin/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:odin/ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the creditsUsageGet operation.
     * @callback moduleodin/odin_api/CreditsApi~creditsUsageGetCallback
     * @param {String} error Error message, if any.
     * @param {module:odin/models/TokensUserTokenStats{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the user&#x27;s credit usage details
     * Get the user&#x27;s credit usage details
     * @param {module:odin/odin_api/CreditsApi~creditsUsageGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    creditsUsageGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TokensUserTokenStats;

      return this.apiClient.callApi(
        '/credits/usage', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}