/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import ExposedBucketAPIResponse from '../models/ExposedBucketAPIResponse';
import ExposedCountRequest from '../models/ExposedCountRequest';
import ExposedSearchRequest from '../models/ExposedSearchRequest';
import ExposedSummaryRequest from '../models/ExposedSummaryRequest';
import InlineResponse2005 from '../models/InlineResponse2005';
import InlineResponse2006 from '../models/InlineResponse2006';

/**
* ExposedBuckets service.
* @module odin/odin_api/ExposedBucketsApi
* @version 1.0
*/
export default class ExposedBucketsApi {

    /**
    * Constructs a new ExposedBucketsApi. 
    * @alias module:odin/odin_api/ExposedBucketsApi
    * @class
    * @param {module:odin/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:odin/ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the exposedBucketsCountPost operation.
     * @callback moduleodin/odin_api/ExposedBucketsApi~exposedBucketsCountPostCallback
     * @param {String} error Error message, if any.
     * @param {module:odin/models/InlineResponse2005{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get exposed bucket count
     * Get exposed bucket count according to provided filters
     * @param {module:odin/models/ExposedCountRequest} body Count Request
     * @param {module:odin/odin_api/ExposedBucketsApi~exposedBucketsCountPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    exposedBucketsCountPost(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling exposedBucketsCountPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['*/*'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2005;

      return this.apiClient.callApi(
        '/exposed/buckets/count', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the exposedBucketsSearchPost operation.
     * @callback moduleodin/odin_api/ExposedBucketsApi~exposedBucketsSearchPostCallback
     * @param {String} error Error message, if any.
     * @param {module:odin/models/ExposedBucketAPIResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search exposed buckets
     * Search exposed buckets according to provided filters Search across categories {img, aud, vid, font, doc, src, web, bkup, dbdump} Search across labels {credential, financial, pii, legal, ip, medical, hr, report, confidential, backup, compromised, vulnerable} Search across providers {aws, gcp, do, linode}
     * @param {module:odin/models/ExposedSearchRequest} body Search Query
     * @param {module:odin/odin_api/ExposedBucketsApi~exposedBucketsSearchPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    exposedBucketsSearchPost(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling exposedBucketsSearchPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['*/*'];
      let accepts = ['application/json'];
      let returnType = ExposedBucketAPIResponse;

      return this.apiClient.callApi(
        '/exposed/buckets/search', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the exposedBucketsSummaryPost operation.
     * @callback moduleodin/odin_api/ExposedBucketsApi~exposedBucketsSummaryPostCallback
     * @param {String} error Error message, if any.
     * @param {module:odin/models/InlineResponse2006{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Exposed buckets summary
     * Get Returns exposed buckets aggregated count according to filters
     * @param {module:odin/models/ExposedSummaryRequest} body Summary Request
     * @param {module:odin/odin_api/ExposedBucketsApi~exposedBucketsSummaryPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    exposedBucketsSummaryPost(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling exposedBucketsSummaryPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = ['*/*'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2006;

      return this.apiClient.callApi(
        '/exposed/buckets/summary', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}