/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import FieldsErrorResponse from '../models/FieldsErrorResponse';
import InlineResponse2007 from '../models/InlineResponse2007';
import InlineResponse2008 from '../models/InlineResponse2008';

/**
* Fields service.
* @module odin/odin_api/FieldsApi
* @version 1.0
*/
export default class FieldsApi {

    /**
    * Constructs a new FieldsApi. 
    * @alias module:odin/odin_api/FieldsApi
    * @class
    * @param {module:odin/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:odin/ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the exposedCategoryGet operation.
     * @callback moduleodin/odin_api/FieldsApi~exposedCategoryGetCallback
     * @param {String} error Error message, if any.
     * @param {module:odin/models/InlineResponse2007{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the fields for exposed
     * Get the list of fields that can be used to query on exposed buckets and files
     * @param {String} category get the category
     * @param {module:odin/odin_api/FieldsApi~exposedCategoryGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    exposedCategoryGet(category, callback) {
      
      let postBody = null;
      // verify the required parameter 'category' is set
      if (category === undefined || category === null) {
        throw new Error("Missing the required parameter 'category' when calling exposedCategoryGet");
      }

      let pathParams = {
        'category': category
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/exposed/{category}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the fieldsCertificatesCategoryGet operation.
     * @callback moduleodin/odin_api/FieldsApi~fieldsCertificatesCategoryGetCallback
     * @param {String} error Error message, if any.
     * @param {module:odin/models/InlineResponse2008{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the fields for certificates
     * Get the list of fields to query upon certificates
     * @param {String} category get the category
     * @param {module:odin/odin_api/FieldsApi~fieldsCertificatesCategoryGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    fieldsCertificatesCategoryGet(category, callback) {
      
      let postBody = null;
      // verify the required parameter 'category' is set
      if (category === undefined || category === null) {
        throw new Error("Missing the required parameter 'category' when calling fieldsCertificatesCategoryGet");
      }

      let pathParams = {
        'category': category
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2008;

      return this.apiClient.callApi(
        '/fields/certificates/{category}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the fieldsHostsCategoryGet operation.
     * @callback moduleodin/odin_api/FieldsApi~fieldsHostsCategoryGetCallback
     * @param {String} error Error message, if any.
     * @param {module:odin/models/InlineResponse2008{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the fields for hosts
     * Get the list of fields to query on host
     * @param {String} category get the category
     * @param {module:odin/odin_api/FieldsApi~fieldsHostsCategoryGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    fieldsHostsCategoryGet(category, callback) {
      
      let postBody = null;
      // verify the required parameter 'category' is set
      if (category === undefined || category === null) {
        throw new Error("Missing the required parameter 'category' when calling fieldsHostsCategoryGet");
      }

      let pathParams = {
        'category': category
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2008;

      return this.apiClient.callApi(
        '/fields/hosts/{category}/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}