/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Odin);
  }
}(this, function(expect, Odin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Odin.CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner', function() {
    it('should create an instance of CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner', function() {
      // uncomment below and update the code to test CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner
      //var instance = new Odin.CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner();
      //expect(instance).to.be.a(Odin.CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner);
    });

    it('should have the property cps (base name: "cps")', function() {
      // uncomment below and update the code to test the property cps
      //var instance = new Odin.CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Odin.CertificateCertificateHashResponseDataCertificateExtensionsCertificatePoliciesInner();
      //expect(instance).to.be();
    });

  });

}));
