/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/odin/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/odin/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdinApis);
  }
}(this, function(expect, OdinApis) {
  'use strict';

  var instance;

  describe('odin', function() {
    describe('DnsDNSCountRequest', function() {
      beforeEach(function() {
        instance = new OdinApis.DnsDNSCountRequest();
      });

      it('should create an instance of DnsDNSCountRequest', function() {
        // TODO: update the code to test DnsDNSCountRequest
        expect(instance).to.be.a(OdinApis.DnsDNSCountRequest);
      });

      it('should have the property domain (base name: "domain")', function() {
        // TODO: update the code to test the property domain
        expect(instance).to.have.property('domain');
        // expect(instance.domain).to.be(expectedValueLiteral);
      });

      it('should have the property publishedAfter (base name: "publishedAfter")', function() {
        // TODO: update the code to test the property publishedAfter
        expect(instance).to.have.property('publishedAfter');
        // expect(instance.publishedAfter).to.be(expectedValueLiteral);
      });

      it('should have the property publishedBefore (base name: "publishedBefore")', function() {
        // TODO: update the code to test the property publishedBefore
        expect(instance).to.have.property('publishedBefore');
        // expect(instance.publishedBefore).to.be(expectedValueLiteral);
      });

    });
  });

}));
