/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/odin/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/odin/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdinApis);
  }
}(this, function(expect, OdinApis) {
  'use strict';

  var instance;

  describe('odin', function() {
    describe('ExposedAggregate', function() {
      beforeEach(function() {
        instance = new OdinApis.ExposedAggregate();
      });

      it('should create an instance of ExposedAggregate', function() {
        // TODO: update the code to test ExposedAggregate
        expect(instance).to.be.a(OdinApis.ExposedAggregate);
      });

      it('should have the property buckets (base name: "buckets")', function() {
        // TODO: update the code to test the property buckets
        expect(instance).to.have.property('buckets');
        // expect(instance.buckets).to.be(expectedValueLiteral);
      });

      it('should have the property docCountErrorUpperBound (base name: "doc_count_error_upper_bound")', function() {
        // TODO: update the code to test the property docCountErrorUpperBound
        expect(instance).to.have.property('docCountErrorUpperBound');
        // expect(instance.docCountErrorUpperBound).to.be(expectedValueLiteral);
      });

      it('should have the property sumOtherDocCount (base name: "sum_other_doc_count")', function() {
        // TODO: update the code to test the property sumOtherDocCount
        expect(instance).to.have.property('sumOtherDocCount');
        // expect(instance.sumOtherDocCount).to.be(expectedValueLiteral);
      });

    });
  });

}));
