/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/odin/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/odin/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdinApis);
  }
}(this, function(expect, OdinApis) {
  'use strict';

  var instance;

  describe('odin', function() {
    describe('IpservicesHostsIpDetailsResponseDataServices', function() {
      beforeEach(function() {
        instance = new OdinApis.IpservicesHostsIpDetailsResponseDataServices();
      });

      it('should create an instance of IpservicesHostsIpDetailsResponseDataServices', function() {
        // TODO: update the code to test IpservicesHostsIpDetailsResponseDataServices
        expect(instance).to.be.a(OdinApis.IpservicesHostsIpDetailsResponseDataServices);
      });

      it('should have the property meta (base name: "_meta")', function() {
        // TODO: update the code to test the property meta
        expect(instance).to.have.property('meta');
        // expect(instance.meta).to.be(expectedValueLiteral);
      });

      it('should have the property cve (base name: "cve")', function() {
        // TODO: update the code to test the property cve
        expect(instance).to.have.property('cve');
        // expect(instance.cve).to.be(expectedValueLiteral);
      });

      it('should have the property extraInfo (base name: "extra_info")', function() {
        // TODO: update the code to test the property extraInfo
        expect(instance).to.have.property('extraInfo');
        // expect(instance.extraInfo).to.be(expectedValueLiteral);
      });

      it('should have the property lastUpdatedAt (base name: "last_updated_at")', function() {
        // TODO: update the code to test the property lastUpdatedAt
        expect(instance).to.have.property('lastUpdatedAt');
        // expect(instance.lastUpdatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property modules (base name: "modules")', function() {
        // TODO: update the code to test the property modules
        expect(instance).to.have.property('modules');
        // expect(instance.modules).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property port (base name: "port")', function() {
        // TODO: update the code to test the property port
        expect(instance).to.have.property('port');
        // expect(instance.port).to.be(expectedValueLiteral);
      });

      it('should have the property product (base name: "product")', function() {
        // TODO: update the code to test the property product
        expect(instance).to.have.property('product');
        // expect(instance.product).to.be(expectedValueLiteral);
      });

      it('should have the property protocol (base name: "protocol")', function() {
        // TODO: update the code to test the property protocol
        expect(instance).to.have.property('protocol');
        // expect(instance.protocol).to.be(expectedValueLiteral);
      });

      it('should have the property softwares (base name: "softwares")', function() {
        // TODO: update the code to test the property softwares
        expect(instance).to.have.property('softwares');
        // expect(instance.softwares).to.be(expectedValueLiteral);
      });

      it('should have the property tunnel (base name: "tunnel")', function() {
        // TODO: update the code to test the property tunnel
        expect(instance).to.have.property('tunnel');
        // expect(instance.tunnel).to.be(expectedValueLiteral);
      });

      it('should have the property version (base name: "version")', function() {
        // TODO: update the code to test the property version
        expect(instance).to.have.property('version');
        // expect(instance.version).to.be(expectedValueLiteral);
      });

    });
  });

}));
