/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/odin/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/odin/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdinApis);
  }
}(this, function(expect, OdinApis) {
  'use strict';

  var instance;

  describe('odin', function() {
    describe('IpservicesHostsIpDetailsResponseData', function() {
      beforeEach(function() {
        instance = new OdinApis.IpservicesHostsIpDetailsResponseData();
      });

      it('should create an instance of IpservicesHostsIpDetailsResponseData', function() {
        // TODO: update the code to test IpservicesHostsIpDetailsResponseData
        expect(instance).to.be.a(OdinApis.IpservicesHostsIpDetailsResponseData);
      });

      it('should have the property asn (base name: "asn")', function() {
        // TODO: update the code to test the property asn
        expect(instance).to.have.property('asn');
        // expect(instance.asn).to.be(expectedValueLiteral);
      });

      it('should have the property asnUpdatedAt (base name: "asn_updated_at")', function() {
        // TODO: update the code to test the property asnUpdatedAt
        expect(instance).to.have.property('asnUpdatedAt');
        // expect(instance.asnUpdatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property banner (base name: "banner")', function() {
        // TODO: update the code to test the property banner
        expect(instance).to.have.property('banner');
        // expect(instance.banner).to.be(expectedValueLiteral);
      });

      it('should have the property domains (base name: "domains")', function() {
        // TODO: update the code to test the property domains
        expect(instance).to.have.property('domains');
        // expect(instance.domains).to.be(expectedValueLiteral);
      });

      it('should have the property hostnames (base name: "hostnames")', function() {
        // TODO: update the code to test the property hostnames
        expect(instance).to.have.property('hostnames');
        // expect(instance.hostnames).to.be(expectedValueLiteral);
      });

      it('should have the property ip (base name: "ip")', function() {
        // TODO: update the code to test the property ip
        expect(instance).to.have.property('ip');
        // expect(instance.ip).to.be(expectedValueLiteral);
      });

      it('should have the property isIpv4 (base name: "is_ipv4")', function() {
        // TODO: update the code to test the property isIpv4
        expect(instance).to.have.property('isIpv4');
        // expect(instance.isIpv4).to.be(expectedValueLiteral);
      });

      it('should have the property isIpv6 (base name: "is_ipv6")', function() {
        // TODO: update the code to test the property isIpv6
        expect(instance).to.have.property('isIpv6');
        // expect(instance.isIpv6).to.be(expectedValueLiteral);
      });

      it('should have the property isVuln (base name: "is_vuln")', function() {
        // TODO: update the code to test the property isVuln
        expect(instance).to.have.property('isVuln');
        // expect(instance.isVuln).to.be(expectedValueLiteral);
      });

      it('should have the property lastUpdatedAt (base name: "last_updated_at")', function() {
        // TODO: update the code to test the property lastUpdatedAt
        expect(instance).to.have.property('lastUpdatedAt');
        // expect(instance.lastUpdatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property location (base name: "location")', function() {
        // TODO: update the code to test the property location
        expect(instance).to.have.property('location');
        // expect(instance.location).to.be(expectedValueLiteral);
      });

      it('should have the property locationUpdatedAt (base name: "location_updated_at")', function() {
        // TODO: update the code to test the property locationUpdatedAt
        expect(instance).to.have.property('locationUpdatedAt');
        // expect(instance.locationUpdatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property scanId (base name: "scan_id")', function() {
        // TODO: update the code to test the property scanId
        expect(instance).to.have.property('scanId');
        // expect(instance.scanId).to.be(expectedValueLiteral);
      });

      it('should have the property services (base name: "services")', function() {
        // TODO: update the code to test the property services
        expect(instance).to.have.property('services');
        // expect(instance.services).to.be(expectedValueLiteral);
      });

      it('should have the property servicesHash (base name: "services_hash")', function() {
        // TODO: update the code to test the property servicesHash
        expect(instance).to.have.property('servicesHash');
        // expect(instance.servicesHash).to.be(expectedValueLiteral);
      });

      it('should have the property tags (base name: "tags")', function() {
        // TODO: update the code to test the property tags
        expect(instance).to.have.property('tags');
        // expect(instance.tags).to.be(expectedValueLiteral);
      });

      it('should have the property whois (base name: "whois")', function() {
        // TODO: update the code to test the property whois
        expect(instance).to.have.property('whois');
        // expect(instance.whois).to.be(expectedValueLiteral);
      });

      it('should have the property whoisUpdatedAt (base name: "whois_updated_at")', function() {
        // TODO: update the code to test the property whoisUpdatedAt
        expect(instance).to.have.property('whoisUpdatedAt');
        // expect(instance.whoisUpdatedAt).to.be(expectedValueLiteral);
      });

    });
  });

}));
