/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/odin/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/odin/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdinApis);
  }
}(this, function(expect, OdinApis) {
  'use strict';

  var instance;

  describe('odin', function() {
    describe('IpservicesHostsIpDetailsResponseDataHostnames', function() {
      beforeEach(function() {
        instance = new OdinApis.IpservicesHostsIpDetailsResponseDataHostnames();
      });

      it('should create an instance of IpservicesHostsIpDetailsResponseDataHostnames', function() {
        // TODO: update the code to test IpservicesHostsIpDetailsResponseDataHostnames
        expect(instance).to.be.a(OdinApis.IpservicesHostsIpDetailsResponseDataHostnames);
      });

      it('should have the property lastUpdatedAt (base name: "last_updated_at")', function() {
        // TODO: update the code to test the property lastUpdatedAt
        expect(instance).to.have.property('lastUpdatedAt');
        // expect(instance.lastUpdatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

    });
  });

}));
