/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Odin);
  }
}(this, function(expect, Odin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Odin.IpservicesIPSummaryData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IpservicesIPSummaryData', function() {
    it('should create an instance of IpservicesIPSummaryData', function() {
      // uncomment below and update the code to test IpservicesIPSummaryData
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be.a(Odin.IpservicesIPSummaryData);
    });

    it('should have the property asn (base name: "asn")', function() {
      // uncomment below and update the code to test the property asn
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property asnUpdatedAt (base name: "asn_updated_at")', function() {
      // uncomment below and update the code to test the property asnUpdatedAt
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property banner (base name: "banner")', function() {
      // uncomment below and update the code to test the property banner
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property domains (base name: "domains")', function() {
      // uncomment below and update the code to test the property domains
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property hostnames (base name: "hostnames")', function() {
      // uncomment below and update the code to test the property hostnames
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property ip (base name: "ip")', function() {
      // uncomment below and update the code to test the property ip
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property isIpv4 (base name: "is_ipv4")', function() {
      // uncomment below and update the code to test the property isIpv4
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property isIpv6 (base name: "is_ipv6")', function() {
      // uncomment below and update the code to test the property isIpv6
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property isVuln (base name: "is_vuln")', function() {
      // uncomment below and update the code to test the property isVuln
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdatedAt (base name: "last_updated_at")', function() {
      // uncomment below and update the code to test the property lastUpdatedAt
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property locationUpdatedAt (base name: "location_updated_at")', function() {
      // uncomment below and update the code to test the property locationUpdatedAt
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property scanId (base name: "scan_id")', function() {
      // uncomment below and update the code to test the property scanId
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property services (base name: "services")', function() {
      // uncomment below and update the code to test the property services
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property servicesHash (base name: "services_hash")', function() {
      // uncomment below and update the code to test the property servicesHash
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property whois (base name: "whois")', function() {
      // uncomment below and update the code to test the property whois
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

    it('should have the property whoisUpdatedAt (base name: "whois_updated_at")', function() {
      // uncomment below and update the code to test the property whoisUpdatedAt
      //var instance = new Odin.IpservicesIPSummaryData();
      //expect(instance).to.be();
    });

  });

}));
