/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/odin/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/odin/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdinApis);
  }
}(this, function(expect, OdinApis) {
  'use strict';

  var instance;

  describe('odin', function() {
    describe('IpservicesHostsSearchDataAsn', function() {
      beforeEach(function() {
        instance = new OdinApis.IpservicesHostsSearchDataAsn();
      });

      it('should create an instance of IpservicesHostsSearchDataAsn', function() {
        // TODO: update the code to test IpservicesHostsSearchDataAsn
        expect(instance).to.be.a(OdinApis.IpservicesHostsSearchDataAsn);
      });

      it('should have the property countryCode (base name: "country_code")', function() {
        // TODO: update the code to test the property countryCode
        expect(instance).to.have.property('countryCode');
        // expect(instance.countryCode).to.be(expectedValueLiteral);
      });

      it('should have the property _number (base name: "number")', function() {
        // TODO: update the code to test the property _number
        expect(instance).to.have.property('_number');
        // expect(instance._number).to.be(expectedValueLiteral);
      });

      it('should have the property organization (base name: "organization")', function() {
        // TODO: update the code to test the property organization
        expect(instance).to.have.property('organization');
        // expect(instance.organization).to.be(expectedValueLiteral);
      });

    });
  });

}));
