/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Odin);
  }
}(this, function(expect, Odin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Odin.SchemaAudit();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SchemaAudit', function() {
    it('should create an instance of SchemaAudit', function() {
      // uncomment below and update the code to test SchemaAudit
      //var instance = new Odin.SchemaAudit();
      //expect(instance).to.be.a(Odin.SchemaAudit);
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new Odin.SchemaAudit();
      //expect(instance).to.be();
    });

    it('should have the property expiresDate (base name: "expires_date")', function() {
      // uncomment below and update the code to test the property expiresDate
      //var instance = new Odin.SchemaAudit();
      //expect(instance).to.be();
    });

    it('should have the property isModified (base name: "is_modified")', function() {
      // uncomment below and update the code to test the property isModified
      //var instance = new Odin.SchemaAudit();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new Odin.SchemaAudit();
      //expect(instance).to.be();
    });

  });

}));
