/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Odin);
  }
}(this, function(expect, Odin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Odin.SchemaDomainWhoisResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SchemaDomainWhoisResponse', function() {
    it('should create an instance of SchemaDomainWhoisResponse', function() {
      // uncomment below and update the code to test SchemaDomainWhoisResponse
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be.a(Odin.SchemaDomainWhoisResponse);
    });

    it('should have the property administrativeContact (base name: "administrative_contact")', function() {
      // uncomment below and update the code to test the property administrativeContact
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property auditedFields (base name: "audited_fields")', function() {
      // uncomment below and update the code to test the property auditedFields
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property billingContact (base name: "billing_contact")', function() {
      // uncomment below and update the code to test the property billingContact
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdDate (base name: "created_date")', function() {
      // uncomment below and update the code to test the property createdDate
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property domainName (base name: "domain_name")', function() {
      // uncomment below and update the code to test the property domainName
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property domainStatus (base name: "domain_status")', function() {
      // uncomment below and update the code to test the property domainStatus
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property expiresDate (base name: "expires_date")', function() {
      // uncomment below and update the code to test the property expiresDate
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property nameServers (base name: "name_servers")', function() {
      // uncomment below and update the code to test the property nameServers
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property rawData (base name: "raw_data")', function() {
      // uncomment below and update the code to test the property rawData
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property registrantContact (base name: "registrant_contact")', function() {
      // uncomment below and update the code to test the property registrantContact
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property registrar (base name: "registrar")', function() {
      // uncomment below and update the code to test the property registrar
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property technicalContact (base name: "technical_contact")', function() {
      // uncomment below and update the code to test the property technicalContact
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property tld (base name: "tld")', function() {
      // uncomment below and update the code to test the property tld
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

    it('should have the property updatedDate (base name: "updated_date")', function() {
      // uncomment below and update the code to test the property updatedDate
      //var instance = new Odin.SchemaDomainWhoisResponse();
      //expect(instance).to.be();
    });

  });

}));
