/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Odin);
  }
}(this, function(expect, Odin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Odin.ServiceService();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServiceService', function() {
    it('should create an instance of ServiceService', function() {
      // uncomment below and update the code to test ServiceService
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be.a(Odin.ServiceService);
    });

    it('should have the property meta (base name: "_meta")', function() {
      // uncomment below and update the code to test the property meta
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property asn (base name: "asn")', function() {
      // uncomment below and update the code to test the property asn
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property asnUpdatedAt (base name: "asn_updated_at")', function() {
      // uncomment below and update the code to test the property asnUpdatedAt
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property banners (base name: "banners")', function() {
      // uncomment below and update the code to test the property banners
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property cve (base name: "cve")', function() {
      // uncomment below and update the code to test the property cve
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property domains (base name: "domains")', function() {
      // uncomment below and update the code to test the property domains
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property extraInfo (base name: "extra_info")', function() {
      // uncomment below and update the code to test the property extraInfo
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property hostnames (base name: "hostnames")', function() {
      // uncomment below and update the code to test the property hostnames
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property ip (base name: "ip")', function() {
      // uncomment below and update the code to test the property ip
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property isIpv4 (base name: "is_ipv4")', function() {
      // uncomment below and update the code to test the property isIpv4
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property isIpv6 (base name: "is_ipv6")', function() {
      // uncomment below and update the code to test the property isIpv6
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property isVuln (base name: "is_vuln")', function() {
      // uncomment below and update the code to test the property isVuln
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdatedAt (base name: "last_updated_at")', function() {
      // uncomment below and update the code to test the property lastUpdatedAt
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property locationUpdatedAt (base name: "location_updated_at")', function() {
      // uncomment below and update the code to test the property locationUpdatedAt
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property modules (base name: "modules")', function() {
      // uncomment below and update the code to test the property modules
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property port (base name: "port")', function() {
      // uncomment below and update the code to test the property port
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property product (base name: "product")', function() {
      // uncomment below and update the code to test the property product
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property protocol (base name: "protocol")', function() {
      // uncomment below and update the code to test the property protocol
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property scanId (base name: "scan_id")', function() {
      // uncomment below and update the code to test the property scanId
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property softwares (base name: "softwares")', function() {
      // uncomment below and update the code to test the property softwares
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property tunnel (base name: "tunnel")', function() {
      // uncomment below and update the code to test the property tunnel
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property whois (base name: "whois")', function() {
      // uncomment below and update the code to test the property whois
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

    it('should have the property whoisUpdatedAt (base name: "whois_updated_at")', function() {
      // uncomment below and update the code to test the property whoisUpdatedAt
      //var instance = new Odin.ServiceService();
      //expect(instance).to.be();
    });

  });

}));
