/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/odin/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/odin/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdinApis);
  }
}(this, function(expect, OdinApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OdinApis.CertificateApi();
  });

  describe('odin', function() {
    describe('CertificateApi', function() {
      describe('certificatesCountPost', function() {
        it('should call certificatesCountPost successfully', function(done) {
          // TODO: uncomment, update parameter values for certificatesCountPost call and complete the assertions
          /*

          instance.certificatesCountPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OdinApis.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('certificatesHashGet', function() {
        it('should call certificatesHashGet successfully', function(done) {
          // TODO: uncomment, update parameter values for certificatesHashGet call and complete the assertions
          /*

          instance.certificatesHashGet(hash, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OdinApis.CertificateAPIResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('certificatesScrollNextPost', function() {
        it('should call certificatesScrollNextPost successfully', function(done) {
          // TODO: uncomment, update parameter values for certificatesScrollNextPost call and complete the assertions
          /*

          instance.certificatesScrollNextPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OdinApis.InlineResponse2002);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('certificatesScrollPost', function() {
        it('should call certificatesScrollPost successfully', function(done) {
          // TODO: uncomment, update parameter values for certificatesScrollPost call and complete the assertions
          /*

          instance.certificatesScrollPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OdinApis.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('certificatesSearchPost', function() {
        it('should call certificatesSearchPost successfully', function(done) {
          // TODO: uncomment, update parameter values for certificatesSearchPost call and complete the assertions
          /*

          instance.certificatesSearchPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OdinApis.InlineResponse2003);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('certificatesSummaryPost', function() {
        it('should call certificatesSummaryPost successfully', function(done) {
          // TODO: uncomment, update parameter values for certificatesSummaryPost call and complete the assertions
          /*

          instance.certificatesSummaryPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OdinApis.InlineResponse2004);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
