/*
 * ODIN APIs
 * APIs fetchs the data based on query
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/odin/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/odin/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OdinApis);
  }
}(this, function(expect, OdinApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OdinApis.CreditsApi();
  });

  describe('odin', function() {
    describe('CreditsApi', function() {
      describe('creditsUsageGet', function() {
        it('should call creditsUsageGet successfully', function(done) {
          // TODO: uncomment creditsUsageGet call and complete the assertions
          /*

          instance.creditsUsageGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(OdinApis.TokensUserTokenStats);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
