/**
 * ODIN
 * APIs fetchs the data based on query
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Odin);
  }
}(this, function(expect, Odin) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Odin.DomainApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DomainApi', function() {
    describe('v1DomainCountPost', function() {
      it('should call v1DomainCountPost successfully', function(done) {
        //uncomment below and update the code to test v1DomainCountPost
        //instance.v1DomainCountPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1DomainSearchPost', function() {
      it('should call v1DomainSearchPost successfully', function(done) {
        //uncomment below and update the code to test v1DomainSearchPost
        //instance.v1DomainSearchPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1DomainSubdomainCountPost', function() {
      it('should call v1DomainSubdomainCountPost successfully', function(done) {
        //uncomment below and update the code to test v1DomainSubdomainCountPost
        //instance.v1DomainSubdomainCountPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1DomainSubdomainSearchPost', function() {
      it('should call v1DomainSubdomainSearchPost successfully', function(done) {
        //uncomment below and update the code to test v1DomainSubdomainSearchPost
        //instance.v1DomainSubdomainSearchPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1DomainWhoisDomainNameGet', function() {
      it('should call v1DomainWhoisDomainNameGet successfully', function(done) {
        //uncomment below and update the code to test v1DomainWhoisDomainNameGet
        //instance.v1DomainWhoisDomainNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1DomainWhoisDomainNameHistoricalGet', function() {
      it('should call v1DomainWhoisDomainNameHistoricalGet successfully', function(done) {
        //uncomment below and update the code to test v1DomainWhoisDomainNameHistoricalGet
        //instance.v1DomainWhoisDomainNameHistoricalGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1DomainWhoisDomainNameIsExpiredGet', function() {
      it('should call v1DomainWhoisDomainNameIsExpiredGet successfully', function(done) {
        //uncomment below and update the code to test v1DomainWhoisDomainNameIsExpiredGet
        //instance.v1DomainWhoisDomainNameIsExpiredGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1DomainWhoisDomainNameIsRegisteredGet', function() {
      it('should call v1DomainWhoisDomainNameIsRegisteredGet successfully', function(done) {
        //uncomment below and update the code to test v1DomainWhoisDomainNameIsRegisteredGet
        //instance.v1DomainWhoisDomainNameIsRegisteredGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
